// evidence-kwinana.js — Assessment evidence for Kwinana.
//
// Structure per indicator:
//   An array of assessment rounds, most recent first.
//   Each round: { date, score, paragraphs: ["para 1", "para 2", ...] }
//
// To add a new assessment round, prepend a new object to the array.
// The previous round is preserved automatically as history.

window.CITY_EVIDENCE = {

  "renewable-energy-generation": [
    {
      date: "August 2026",
      score: 2,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Poor progress towards 2035 requirements. Less than 25% of required capacity is in development, with 15% or less approved and 10% or less in construction or operating.</li><li><strong>2</strong> – Improving progress towards 2035 requirements. Between 25% and 50% of required capacity is in development, with 15–40% approved and 10–25% in construction or operating.</li><li><strong>3</strong> – Moderate progress towards 2035 requirements. Between 50% and 75% of required capacity is in development, with 40–60% approved and 25–40% in construction or operating.</li><li><strong>4</strong> – Strong progress towards 2035 requirements. Between 75% and 100% of required capacity is in development, with 60–85% approved and 40–50% in construction or operating.</li><li><strong>5</strong> – Exemplary progress towards 2035 requirements. More than 100% of required capacity is in development, with over 85% approved and over 50% in construction or operating.</li></ul>",
        "The SWIS has a strong pipeline of renewable energy projects in-development, but prioritisation for storage projects, system planning inconsistencies and lack of industrial power purchase agreements (PPAs) have hindered delivery. We therefore score it as 2.",
        "The renewable energy generation required to power Kwinana will be housed in the wheatbelt and mid-west regions of the SWIS. The pipeline of projects in-development in this footprint is substantial, meeting 160% of 2035 regional requirements according to BZE analysis. However, the implementation is lagging. Only 30% of 2035 requirements have received development approval, and just 8% is in construction or operation. Since the end of 2020, only one wind farm and a single solar farm have been constructed – totalling just 205 MW in nameplate capacity.",
        "A number of factors have contributed to this lag: storage prioritisation in an isolated grid; system planning inconsistency; connection process bottlenecks; and workforce and contractor capacity constraints, with tradespeople on a 3–4 year lag.",
        "Despite these headwinds, there are reasons for optimism. State-level approvals are proceeding quickly, with recent estimates placing median approval times at approximately six months for wind farms and two months for solar farms. Since October, the cumulative capacity of projects with development approval has risen by 50%. Western Power has introduced a Critical Projects framework within its connection process to prioritise connection-ready projects. In parallel, Synergy is progressing a suite of large-scale projects, including the proposed Tathra Wind and Solar Farms, which secured state-level approvals within four months. Synergy and the Water Corporation also signed PPAs to support the development of three other wind farms in the state's Mid-West and Wheatbelt regions, totalling over 1 GW of generation capacity. Delivery of many of these projects, however, is contingent on completion of the Clean Energy Link – North transmission upgrade, required to relieve grid constraints north of Perth.",
        "For Kwinana's renewable energy readiness to improve, a greater share of projects must progress to construction. Grid connection timelines must continue to fall, industrial electrification and green industry strategies should be leveraged to stimulate power purchase agreements and accelerate projects toward final investment decision, and the 2027 Whole of System Plan must deliver a more transparent and sequenced infrastructure development plan.",
      ],
    },
  ],

  "transmission-network": [
    {
      date: "August 2026",
      score: 2,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal planning. Transmission tracking to meet approximately 25–50% of industrial demand.</li><li><strong>2</strong> – Basic planning. Transmission tracking to meet more than 50% of industrial demand.</li><li><strong>3</strong> – Moderate planning. Transmission tracking to meet electrification of existing industry and up to 20% additional demand.</li><li><strong>4</strong> – Strong planning. Transmission on track for 100% electrification of existing industry and 20–50% additional demand for new green industries.</li><li><strong>5</strong> – Exemplary planning. Transmission on track for 100% of needs of existing and new entrant industries.</li></ul>",
        "The Kwinana precinct is supported by a strong transmission backbone with substantial spare capacity. However, an inconsistent history of system planning within the SWIS has left existing renewable generation constrained, and substantial new investment is now required to unlock additional capacity. While the 2025 SWIS Transmission Plan defines a program of projects over the next decade to address this, delivery schedules – particularly for Phase 2 – remain vague, leaving the overall timeline uncertain. We score it as a 2.",
        "With limited land available for renewable generation within Kwinana and the wider Western Trade Coast (WTC), any Renewable Energy Industrial Precinct will necessarily depend on projects developed across the broader SWIS footprint – particularly in the Mid-West, Central Midlands and West Arthur regions.",
        "Encouragingly, Kwinana and the WTC are supported by a strong 330 kV transmission backbone, with an estimated 1,800 MW of spare import capacity. Yet this strength at the boundary contrasts with congestion within the precinct's internal 132 kV network, which is currently preventing new facilities from connecting. The larger infrastructure challenge, however, lies beyond the precinct: expanding the wider SWIS to accommodate the scale of renewable generation now in development.",
        "The scale and urgency of this build-out reflect the SWIS's recent planning history. The 2020 Whole of System Plan (WOSP) provided a transparent, scenario-based outlook to 2040, concluding that between 0 and 8 GW of additional transmission could be required. However, unlike the National Electricity Market's Integrated System Plan, it did not consolidate these scenarios into a single, clearly sequenced infrastructure pathway. As a result, transmission development has not kept pace with renewable project ambition. Renewable generation in the Mid-West is already constrained, and further projects cannot connect until the network there is reinforced.",
        "Planned updates to the WOSP were subsequently deferred from 2023 to 2025, and now again to 2027. In the interim, Energy Policy WA released two infrastructure blueprints – the 2023 SWIS Demand Assessment and the more recent 2025 SWIS Transmission Plan – which together formalise the Clean Energy Link program as the state's primary transmission expansion pathway. Of particular relevance to Kwinana are the Clean Energy Link – Kwinana Strengthening, Clean Energy Link – North, Clean Energy Link – Moora & Chittering, and Clean Energy Link – East & Collie projects.",
        "These projects provide a firmer infrastructure pathway than previously existed. However, important uncertainties remain. The plans have been released with limited transparency regarding modelling inputs and assumptions, and it is unclear from the public documentation whether they have been robustly tested against multiple demand scenarios. The SWIS Transmission Plan is also notably less ambitious than the earlier SWIS Demand Assessment, and does not provide firm implementation timelines, instead retaining flexibility in response to demand growth. The long lead times associated with transmission infrastructure, combined with an accelerated delivery schedule, will place Western Power under considerable pressure. Delays therefore appear likely, increasing costs for consumers.",
        "For this score to improve, a clearer and more detailed infrastructure sequencing plan is required, providing defined delivery timelines for industry. Greater transparency on the robustness of the Clean Energy Link program – particularly given its reduced scale relative to earlier proposals (330 kV rather than a potential 500 kV backbone) – would also strengthen confidence. Finally, visibility over planned Phase 3 projects is needed to communicate a coherent long-term development pathway for the SWIS.",
      ],
    },
  ],

  "distribution-network": [
    {
      date: "August 2026",
      score: 2,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – No electrification plans, including at the household level.</li><li><strong>2</strong> – Limited electrification planning. Planning for modest consumer energy resource (CER) uptake, but no industry electrification.</li><li><strong>3</strong> – Moderate electrification planning. Planning for high CER uptake, but no industry electrification.</li><li><strong>4</strong> – Strong electrification planning. Planning for 100% CER and modest industry electrification.</li><li><strong>5</strong> – Exemplary electrification planning. Planning for 100% CER, high industry electrification and capacity for new entrants.</li></ul>",
        "The South West Interconnected System has seen strong consumer energy resource (CER) uptake, supported by a growing suite of enabling network policies. However, limited data transparency makes it difficult to assess the degree to which distribution network planning in Kwinana is accounting for these assets and anticipated industrial electrification. We score it as 2.",
        "Distribution networks can grow rapidly to meet emerging demand and constitute approximately 80% of network charges on bills. When supporting Renewable Energy Industrial Precincts, they run optimally when they leverage renewable generation and storage without requiring network expansion, cultivate CER uptake, and incentivise higher network utilisation through appropriate tariffs.",
        "On the residential side, Western Australia fares well. It ranks third nationally in solar and battery installations on a per-household basis, with over 40% of dwellings having rooftop solar installed – enough to meet 21% of all electricity demand over the past year. The state government, Western Power, and Synergy are all taking steps to cultivate further uptake and help consumers get more value from installed assets, including orchestration and market participation through Project Jupiter, battery rebates of $1,300 with virtual power plant options, and 100 fast and ultra-fast electric vehicle chargers.",
        "Despite these positive steps, challenges remain. Residential customers cannot trade on the wholesale market to take advantage of cheap daytime solar, and Synergy's Distributed Energy Buyback Scheme pays just $0.10/kWh during peak periods outside VPP windows, limiting returns on those investments. The Electric Vehicle Council scores WA as 4/10, with particular gaps in suitable tariffs and heavy vehicle charging infrastructure. From a planning perspective, Western Power does not disclose assumed residential electrification and CER uptake in the scenarios which underpin their network modelling in either their Transmission System Plan or Network Opportunities Map.",
        "Industrial electrification has received considerably less support. At Mason Road – Kwinana's majority commercial customer substation – both maximum and minimum system demand are forecast to grow by just 3.4% over the next decade, sitting well below the terminal's 72 MW capacity. A key barrier to increased electrification is the absence of tariffs incentivising daytime industrial demand. Customers with peak demand exceeding 1.5 MVA are charged on that basis regardless of when the peak occurs, creating a cost barrier to technologies such as industrial heat pumps and thermal energy storage.",
        "Customers can access network data via Western Power's Network Capacity Mapping Tool, which provides high-level substation capacity projections over a ten-year horizon. A companion network data spreadsheet, released annually as part of the Network Opportunities Map, adds further detail: peak load and average utilisation forecasts per substation, basic customer categorisation including estimated embedded PV, and five-year average utilisation by medium voltage feeder. Neither tool, however, provides electrification scenarios or transparency around underlying inputs and assumptions.",
        "For Kwinana's distribution readiness to improve, Western Power and other responsible authorities should work toward greater transparency around the inputs and assumptions behind their CER growth and electrification scenarios, and on network capacity tools for private EV charging and flexible electrification, consistent with the direction being taken in NEM networks and AEMO's Integrated System Plan.",
      ],
    },
  ],

  "energy-storage": [
    {
      date: "August 2026",
      score: 3,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Poor progress towards 2035 storage requirements. Less than 25% of required capacity/depth is in development, with 15% or less approved and 10% or less in construction or operating.</li><li><strong>2</strong> – Improving progress towards 2035 storage requirements. Between 25% and 50% of required capacity/depth is in development, with 15–40% approved and 10–25% in construction or operating.</li><li><strong>3</strong> – Moderate progress towards 2035 storage requirements. Between 50% and 75% of required capacity/depth is in development, with 40–60% approved and 25–40% in construction or operating.</li><li><strong>4</strong> – Strong progress towards 2035 storage requirements. Between 75% and 100% of required capacity/depth is in development, with 60–85% approved and 40–50% in construction or operating.</li><li><strong>5</strong> – Exemplary progress towards 2035 storage requirements. Over 100% of required capacity/depth is in development, with more than 85% approved and more than 50% in construction or operating.</li></ul>",
        "Since 2023, utility-scale battery projects have been delivered with regularity in Kwinana and the wider SWIS. However, limited technological diversity – particularly the absence of pumped hydro – means challenges remain in delivering the storage depth required for electrified industry in Kwinana. We therefore score it as 3.",
        "As the world's largest isolated grid, and with minimal hydro resources, the SWIS has prioritised utility-scale batteries to maintain reliability. Since May 2023, a cumulative 0.9 GW / 3.5 GWh of battery capacity has been completed, with an additional 0.5 GW / 2 GWh currently being commissioned.",
        "This momentum is reflected in a strong development pipeline. Measured by discharge capacity (power), projects totalling 295% of 2035 requirements are in development, 162% have received development approval, and 42% are in construction or operation.",
        "However, when assessed by storage energy – which reflects total system depth rather than instantaneous output – the pipeline's performance is weaker. 91% of 2035 storage energy requirements are in development, with 37% approved and 11% in construction or operation. The relative weakness in depth largely reflects the absence of viable pumped hydro development opportunities within the SWIS footprint, as pumped hydro remains the only mature technology capable of delivering very long-duration storage at scale.",
        "Recognising this constraint, the Western Australian Government has opened an Expression of Interest for a 50 MW / 500 MWh vanadium flow battery in Kalgoorlie. Through this initiative, the Government will provide $150 million to support delivery of long-duration storage in the Goldfields and strengthen Western Australia's vanadium supply chain. While not directly servicing Kwinana, initiatives of this nature will be necessary to provide firmed renewable energy to industry.",
        "Other emerging technologies may also play a role. The single largest storage project currently in development in the SWIS – the Three Springs Open Access Energy Storage – will deploy Energy Dome's CO2 storage technology to provide 1 GW / 14 GWh for the SWIS' north. This would constitute a substantial scale-up of this technology, which stores energy by converting CO2 to its liquid form and releases it by using the reverse phase change to drive a turbine, and has only been deployed at MW-scale previously.",
        "For Kwinana's storage readiness to improve, longer-duration technologies must be scaled to ensure the development pipeline can meet system depth requirements over the coming decade and beyond. Grid connection timelines must continue to fall, and consistent, transparent long-term system planning – particularly through the 2027 Whole of System Plan – will be critical to guiding investment.",
      ],
    },
  ],

  "hydrogen-network": [
    {
      date: "August 2026",
      score: 2,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Underinvestment. Projects likely to deliver only a small amount of green hydrogen by 2035.</li><li><strong>2</strong> – Underinvestment. Projects likely to deliver a modest amount of green hydrogen by 2035.</li><li><strong>3</strong> – Investment in place for a high amount of green hydrogen by 2035.</li><li><strong>4</strong> – Projects expected to come online 2030–35, meeting approximately 50% of Green Energy Exports requirements.</li><li><strong>5</strong> – Projects expected to come online 2030–35, meeting 100% of Green Energy Exports requirements.</li></ul>",
        "Despite a flurry of hydrogen project announcements in Kwinana, few have progressed significantly and it remains uncertain how many will proceed to construction. We score it as a 2.",
        "Green hydrogen features prominently in the decarbonisation strategies of several major Kwinana manufacturers, and demand could grow substantially over coming decades. WesCEF's CSBP ammonium nitrate facility, for example, requires approximately 45 kt per year of hydrogen for ammonia production, currently supplied via emissions-intensive steam methane reforming (SMR). This requirement is set to more than double with the completion of Ammonia Plant 3.",
        "Similarly, hydrogen is being trialed as a fuel for decarbonising the calcination stage of alumina refining. Although Alcoa is piloting direct electrification at its Pinjarra refinery, the preferred pathway at commercial scale remains uncertain. Should hydrogen be adopted, Alcoa's remaining refineries could add up to 190 kt per year of demand across the region.",
        "Green iron production has also been proposed for Kwinana, with two ARENA-supported collaborations – Rio Tinto and Calix's ZESTY plant, and Bluescope's Project NeoSmelt – advancing demonstration-scale facilities. These projects are small and do not contribute significantly to near-term hydrogen demand, nor have their proponents committed to commercial deployment locally. However, modelling by ACIL Allen and Baringa suggests hydrogen demand for green commodities within the SWIS could reach 330–380 kt per year over the next decade. Assuming 50% of this demand is in Kwinana and 50% displacement of natural gas at CSBP and Alcoa, demand within the Kwinana precinct and surrounds could approach 325 kt per year by 2035.",
        "Projects have been proposed to meet this potential demand, but most remain at an early stage, and others have stalled. A cumulative 130 kt per year of green hydrogen production capacity is in development; however, only 0.1 kt per year has progressed to construction or beyond. Woodside's H2Perth proposal, submitted in 2023, has since been scaled back and shifted from green hydrogen via electrolysis to blue hydrogen produced from SMR with carbon capture. The only approved pre-construction green hydrogen project is CSBP's 10 MW demonstration electrolyser, stated to produce around 1.5 kt per year. WesCEF is collaborating with APA on the Parmelia Green Hydrogen project to secure future hydrogen supply for CSBP; at full scale this would produce around 110 kt of green hydrogen per year, most of which would be piped 43 km to Kwinana from Nambeelup. However, neither organisation has committed to the project.",
        "For Kwinana to realise its green commodity ambitions, substantial progress will be required in renewable generation, storage and transmission. Without these enabling conditions, hydrogen production will be unable to scale in line with projected demand.",
      ],
    },
  ],

  "water-and-wastewater": [
    {
      date: "August 2026",
      score: 2,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Critical gap. Lack of sufficient existing, planned or committed infrastructure to address demand growth. Precinct's industries make limited use of recycled wastewater or climate-resilient sources. Water needs of host communities ignored.</li><li><strong>2</strong> – Material gap. Planned projects address much of demand growth, but remain unfunded and without binding commitment. Precinct's industries exhibit some use of recycled wastewater and climate-resilient sources. Host community needs are identified but unfunded.</li><li><strong>3</strong> – Moderate. Committed and funded projects progressing, but fall moderately short of anticipated water demand growth. Precinct's industries exhibit moderate use of recycled wastewater and climate-resilient sources. Host community needs are identified and impacts mitigated.</li><li><strong>4</strong> – Strong. Planned and committed projects mostly accommodate water demand for green industry. Precinct's industries exhibit strong use of recycled wastewater and climate-resilient sources. Co-investment in regional water security to support host communities.</li><li><strong>5</strong> – Exemplary. Planned and committed projects fully address water demand for green industry. Precinct's industries exhibit best practice for water circularity and climate-resilience. Full investment in regional water security positively impacts host communities.</li></ul>",
        "With groundwater licenses in Kwinana fully allocated, new climate-resilient sources and wastewater infrastructure should be developed to support anticipated demand growth from the decarbonisation of existing facilities and the arrival of new green industries. We score its water supply and wastewater management readiness as a 2.",
        "The most recent publicly accessible water analysis for Kwinana and the Western Trade Coast (WTC), released in 2016, placed demand at 28.5 GL per year based on 2014 data, rising to 36–52 GL by 2031. Of 2014 demand, 58% was sourced from groundwater, 13% from the Integrated Water Supply System (IWSS), 17% from the Kwinana Water Recycling Plant (KWRP), and 12% from stormwater and industrial reuse. However, the Cockburn aquifer is fully allocated, meaning new supply must be sourced to meet future demand responsibly.",
        "Since then, the industrial landscape has shifted considerably. New facilities – including the Tianqi and Covalent Lithium refineries – have begun operation, and operators such as CSBP and Cockburn Cement have expanded. These are offset by the closure or mothballing of anchor tenants, most notably Alcoa, which held a licence to draw 5.4 GL per year from the Cockburn aquifer. Looking ahead, 9–15 GL of additional demand could be required to entirely decarbonise hydrogen production at CSBP and support new green industries by 2035. Though conclusive data is not publicly available, the broad picture remains unchanged: groundwater is insufficient to support anticipated growth, IWSS capacity is both costly and competes with residential demand, and new climate-resilient supply sources are needed.",
        "Several options have been identified to address this gap. Studies have demonstrated that a managed aquifer recharge program is feasible for the precinct, though the scheme was never progressed beyond this. Water Corporation has separately established the feasibility of expanding KWRP capacity from 6 GL per year to 9.7 GL per year, the development of which was greenlit in June 2026. However, as this is insufficient to cover anticipated growth in water demand, further expansion has been identified as a critical growth enabler in the WTC Infrastructure Strategy.",
        "The precinct's wastewater is currently treated across four separate plants – Kwinana, Rockingham, Peron Point and Woodman Point. These facilities, together with the KWRP, are connected via the Sepia Depression Ocean Outfall Landline (SDOOL), which conveys a total of 70 GL of treated wastewater per year, with the unused remainder discharged to the ocean near Rockingham. The WTC Infrastructure Strategy identifies emerging capacity constraints on the SDOOL that will need to be addressed. Feasibility studies were completed by GHD in 2015, but Water Corporation has not yet committed to the necessary upgrades.",
        "A further consideration concerns the renewable energy projects on which electrified industry in Kwinana will depend. These are expected to be hosted in the Mid-West, Central Midlands and Wheatbelt regions – areas of increasingly high drought vulnerability. There is an opportunity for renewable developers in these regions to contribute to local water security, as has occurred elsewhere in Australia.",
        "For Kwinana's water and wastewater readiness to improve, commitment to and delivery of new climate-resilient infrastructure – beginning with the KWRP upgrades – is essential. The sequencing and scheduling of these improvements should be guided by a new Western Trade Coast heavy industry water supply strategy, one that updates the 2016 analysis in light of a substantially changed tenant landscape and Western Australia's ambitions as a renewable energy superpower.",
      ],
    },
  ],

  "housing": [
    {
      date: "August 2026",
      score: 2,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Critical gap. Severe shortfall of workforce accommodation with no funded delivery mechanism.</li><li><strong>2</strong> – Material gap. Significant shortfall of accommodation capacity relative to project pipeline demand, with no binding legacy commitment or coordinated strategy.</li><li><strong>3</strong> – Developing. Some accommodation strategy in place but shortfalls remain and legacy conversion commitments are limited.</li><li><strong>4</strong> – Strong. Accommodation supply broadly matching pipeline demand, with funded legacy conversion commitments.</li><li><strong>5</strong> – Exemplary. Purpose-built accommodation fully meeting demand, with binding legacy conversion and community housing outcomes secured.</li></ul>",
        "The housing readiness indicator for the Kwinana region is scored as a 2. The precinct catchment has some existing market capacity but is well short of absorbing construction demand from multiple simultaneous projects; the upstream host communities that will house the renewable energy construction workforce have virtually no accommodation capacity at all; and no funded delivery mechanism or binding legacy commitment has been identified in either zone.",
        "In the Kwinana precinct catchment, spanning the Cities of Kwinana, Rockingham, and Cockburn, major projects including Woodside's H2Perth facility (up to 980 peak construction workers) and the CSBP Ammonia Expansion (up to 500 workers) generate a combined peak demand of approximately 1,060 beds. Against usable rental vacancy of around 570 beds, the assessed shortfall is 46%. Perth's rental vacancy rate sat at just 2.6% as of January 2026 (REIWA), with the broader market recorded at 0.6% by SQM Research, among the tightest in the country. None of the major projects has a publicly confirmed accommodation strategy; all are assumed to rely on the private rental market, placing direct pressure on existing residents. The pausing of BP's H2Kwinana project since evidence was collected reduces demand somewhat, but does not materially close the gap given the underlying market tightness.",
        "The more acute constraint is in the upstream host communities. The renewable energy generation required to power Kwinana will be built predominantly across Wheatbelt and Central Midlands LGAs: Dandaragan, Carnamah, Williams, Moora, West Arthur, and Wagin, which are small rural communities with populations ranging from around 550 (Carnamah) to 3,400 (Dandaragan). The committed-and-weighted project pipeline generates an estimated peak construction accommodation demand of approximately 4,600 beds by 2029. Confirmed supply across all six LGAs amounts to fewer than 250 beds, with Carnamah, West Arthur, and Williams recording effective shortfall ratios of 100%. WA State lot activity data for the March 2024 quarter shows zero subdivision activity in most host LGAs, confirming that private residential development will not respond to this demand without deliberate intervention. The Shire of Dandaragan's draft workforce accommodation local planning policy is a meaningful step, but no binding delivery mechanism or proponent obligation exists in any of these communities.",
        "No statutory approvals, ministerial conditions, or project environmental documents reviewed contain binding commitments to deliver workforce accommodation or convert temporary accommodation to community use post-project, in either zone. The South Australian government's Hydrogen Jobs Plan, which required purpose-built worker accommodation in Whyalla with an enforceable legacy conversion to community and tourism use, illustrates what proactive state-level intervention looks like. No equivalent framework currently exists for Kwinana or its host communities.",
        "The housing challenge in Kwinana is a two-zone problem. In the precinct catchment, a near-zero vacancy rental market is being asked to absorb demand from several major concurrent projects without any coordinated accommodation strategy. In the upstream host communities, the gap is more fundamental: there is functionally no accommodation capacity for the construction workforce that will build Kwinana's renewable energy supply chain.",
        "The state government should establish a workforce accommodation framework for the upstream renewable energy build, requiring proponents, through the approvals pathway or a coordinated state-facilitated process, to deliver purpose-built accommodation with binding post-project legacy conversion commitments. Regional Development Commissions, already positioned as administrators of PoweringWA's Community Benefit funds, are well-placed to manage legacy housing outcomes in host communities. In the precinct catchment, major project proponents should develop and publish accommodation strategies as part of their approvals process, with the Kwinana Industries Council a natural vehicle for coordinating shared procurement. Dandaragan's draft local planning policy on workforce accommodation should be supported and extended to other host LGAs as a minimum standard.",
      ],
    },
  ],

  "industry-decarbonisation-plans": [
    {
      date: "August 2026",
      score: 2,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Most companies have plans with no targets and/or not funded (Limited Plan/Insufficient Targets).</li><li><strong>2</strong> – Most companies have plans with targets, but only some are aligned to 75% emissions reduction by 2035 and not all commitments are funded (Basic Plans/Uncertain Implementation Pathways).</li><li><strong>3</strong> – Most companies have plans with targets, and most are aligned to 75% emissions reduction by 2035 and are funded (Intermediate Plans/Developing Momentum).</li><li><strong>4</strong> – All major companies have plans with targets aligned with 75% emissions reduction by 2035, with commitments funded but no internal performance initiatives (Comprehensive Plans/Aligned with Regional Goals).</li><li><strong>5</strong> – All major companies have plans aligned with 75% emissions reduction by 2035, are fully funded and have internal performance initiatives (Leading Practice/Exemplary Industry Leadership).</li></ul>",
        "Kwinana's industrial decarbonisation plans were ranked as 2. This reflects that most energy-intensive manufacturing facilities in the Kwinana Industrial Precinct have published net zero commitments and some interim targets, but none are clearly aligned with a 1.5°C pathway, which we benchmark as a 75% reduction in emissions by 2035 below 2005 levels. While individual action is evident and some initiatives are well-funded, credible facility-level pathways remain limited, and progress depends heavily on breakthrough technologies and affordable firmed renewable energy that are not yet available at the cost or scale required.",
        "Kwinana is globally recognised for its industrial symbiosis: unlike isolated factories, the companies in the precinct operate as an integrated ecosystem in which the waste or by-product of one facility becomes the feedstock of another, underpinning $15.7 billion in combined annual output and 35,000 direct and indirect jobs. This integration is also a source of structural vulnerability: if a major player exits, the impact transmits through the cluster rather than being absorbed by it. The wave of recent closures and curtailments across the precinct makes this risk concrete. Without credible decarbonisation strategies anchored by affordable clean energy, the precinct risks continuing to lose its industrial base through attrition rather than managed transition.",
        "Five active energy-intensive facilities were assessed: CSBP (WesCEF), Cockburn Cement (CRH/Adbri), Covalent Lithium, Tronox, and Coogee Chemicals. CSBP (WesCEF) is the precinct's largest active emitter, producing ammonia, ammonium nitrate, and fertilisers. WesCEF has committed to a 30% reduction in Scope 1 and 2 emissions by 2030 from a 2020 baseline and net zero by 2050, falling short of 75% by 2035. Cockburn Cement (CRH/Adbri) has published a net zero by 2050 roadmap with a 2030 cement emissions intensity target and a commitment to 100% zero-emissions electricity by 2030, and has completed its coal phase-out at Munster. Covalent Lithium, the precinct's newest and largest active emitter at full production, has committed to a linear net zero trajectory by 2050. Tronox has committed to a 50% reduction in Scope 1 and 2 emissions intensity by 2030 and carbon neutrality by 2050. Coogee Chemicals operates a chlor-alkali facility but has not published a net zero target, a formal decarbonisation plan, or a renewable energy commitment.",
        "The Kwinana Industries Council's Carbon Reduction Plan for the Kwinana Industrial Area (CRKIA) is the only collective industrial carbon reduction programme of its kind in Australia, having established a Scope 1 baseline of 7.23 million tonnes CO2-e and completed Phase One data gathering across member companies. This collective approach is a nationally significant asset that the state and Commonwealth governments have rightly supported. To fulfil its potential, however, CRKIA needs to adopt binding interim targets and a specified net zero date; without these, it functions as a coordination forum rather than an accountable decarbonisation plan.",
        "Kwinana's active industrial facilities have laid the foundations of decarbonisation planning, but none operate on a trajectory consistent with 75% emissions reduction by 2035. Individual efforts are real – CSBP's EnviNOx programme and Tronox's TESSKW1 project are well-funded examples – but progress has depended heavily on government grants and co-investment. Access to affordable, firmed renewable energy is the binding constraint for industrial decarbonisation in Kwinana, and neither green electricity nor green hydrogen is available at the cost or scale required. Continued partnership between government and industry, together with mandatory climate reporting, will be important to lift ambition and accountability across the precinct.",
      ],
    },
  ],

  "federal-emissions-commitment": [
    {
      date: "August 2026",
      score: 3,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal commitment (Severe Deficiency).</li><li><strong>2</strong> – Basic commitment (Moderate Deficiency).</li><li><strong>3</strong> – Moderate commitment (Developing).</li><li><strong>4</strong> – Strong commitment (Effective).</li><li><strong>5</strong> – Exemplary commitment (Leading Practice).</li></ul>",
        "The Australian Federal Government's emissions reduction commitment is scored as a 3. This restores the Moderate Commitment rating recorded in the Hunter Regional Readiness Report (May 2025), which was downgraded to a 2 in the Gladstone Regional Readiness Report (October 2025). The Gladstone report was direct about what drove that drop: emissions targets were being undermined by continual approval of new fossil fuel projects and extension of existing ones, notably the recent approval of the North West Shelf project. The North West Shelf approval has not been reversed, and the broader pattern of fossil fuel approvals continues. What has changed is the cumulative weight of federal policy developments since October 2025, which is sufficient to restore the moderate rating while the same structural contradictions prevent it from reaching Strong Commitment.",
        "The most significant development since the Gladstone assessment is Australia's submission of an updated Nationally Determined Contribution in September 2025, targeting a 62–70% reduction in economy-wide emissions below 2005 levels by 2035. This target did not exist at the time of either prior report. It falls short of the 75% benchmark used across this assessment series as the threshold consistent with limiting global warming to 1.5 degrees, but it closes a meaningful portion of that gap and establishes a formal international accountability mechanism. The federal government has also converted its May 2025 re-election mandate into legislative outcomes: EPBC reforms passed in November 2025, and mandatory climate reporting for large corporations commenced. The 2025-26 Budget added substantial sectoral depth, including a $2 billion Green Aluminium Production Credit, a $1 billion Green Iron Investment Fund, and a $2 billion Clean Energy Finance Corporation expansion. The Safeguard Mechanism completed its first full compliance year with covered emissions falling approximately 2.7 Mt, and a review to align the mechanism with the stronger 2035 target is scheduled for 2026-27.",
        "The structural problem remains, however. Australian law still prohibits the Environment Minister from considering climate pollution when assessing new coal and gas projects, which means the 2035 NDC has no enforcement mechanism at the most consequential approval decisions the federal government makes. For Kwinana, the federal picture is directly relevant. The Safeguard Mechanism is the primary federal lever acting on the precinct's heaviest emitters, with WA's SERS explicitly relying on it to drive industrial abatement. The mothballing of the H2Kwinana green hydrogen facility, despite a committed $70 million Capacity Investment Scheme backing, is a reminder that federal investment programs must be supported by demand-side policy and commercial conditions to translate into construction.",
        "To achieve a higher score, the federal government must close the legal gap preventing climate pollution from being considered in fossil fuel project approvals. The 2026-27 Safeguard Mechanism review must result in a materially strengthened instrument calibrated to the 62-70% NDC trajectory, with tighter baselines and a credible annual decline rate. Finally, the green metals investment programs should be backed by binding production targets, converting demand-side incentives into supply-side commitments that industrial regions like Kwinana can plan against.",
      ],
    },
  ],

  "federal-skills-training": [
    {
      date: "August 2026",
      score: 3,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal support (Severe Deficiency).</li><li><strong>2</strong> – Basic support (Moderate Deficiency).</li><li><strong>3</strong> – Moderate support (Developing).</li><li><strong>4</strong> – Strong support (Effective).</li><li><strong>5</strong> – Exemplary support (Leading Practice).</li></ul>",
        "Federal skills and training policy is scored as a 3, maintaining the Moderate Support rating recorded in both the Hunter Regional Readiness Report (May 2025) and the Gladstone Regional Readiness Report (October 2025). The federal framework has grown materially more resourced since the Gladstone assessment, but structural gaps in regional and sector-specific delivery prevent a move to the Strong Support band.",
        "The most significant development since the Gladstone assessment is the replacement of the New Energy Apprenticeships Program (NEAP) by the Key Apprenticeship Program (KAP), a $722.8 million investment announced in the 2025–26 Budget and running from 1 July 2025 to 30 June 2029. The KAP provides financial incentives for apprentices and employers in clean energy priority occupations through its New Energy Apprenticeship stream. The National Skills Agreement – a five-year, $1.2 billion framework explicitly naming clean energy and net zero transformation as priority skills needs – is now in its second year of implementation. Jobs and Skills Australia has continued to build energy transition workforce intelligence with its Clean Energy Generation study.",
        "The structural limitations that held this indicator at 3 in prior reports remain unresolved, and they bear with particular force on the Kwinana context. Critical trades shortages – electricians, riggers, boilermakers, industrial process technicians – are structural and multi-year in their resolution horizon; the KAP helps the entry pipeline but produces qualified tradespeople over a 3–4 year lead time, not immediately. In Western Australia, wage competition from mining and LNG operations continues to drive attrition from the clean energy workforce: workers trained in clean energy trades are systematically attracted to higher-paying roles in the resources sector, and no federal program currently addresses this differential.",
        "The permanent closure of Alcoa's Kwinana aluminium refinery is resulting in substantial direct and indirect job losses continuing through 2026. The displaced workforce – experienced in chemical process engineering, refinery operations, and heavy industrial maintenance – possesses skills that are highly transferable to the clean energy industries expected at the precinct. Yet no federal transition program is specifically targeting this cohort for clean energy redeployment. The Collie Just Transition model, which provides tailored transition plans, skills assessments, and funded training for affected workers, has no federal counterpart for non-coal industrial closures.",
        "To move to the Strong Support band, the federal government must extend the workforce transition planning model beyond coal-region programs to encompass heavy industrial precincts undergoing structural fossil fuel sector exit. This means developing Kwinana-equivalent transition plans for the displaced Alcoa and broader industrial workforce, providing targeted transition funding for industrial-skills cohorts, and establishing transparent, energy-transition-specific workforce outcome reporting.",
      ],
    },
  ],

  "federal-approvals": [
    {
      date: "August 2026",
      score: 3,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal support (Severe Deficiency).</li><li><strong>2</strong> – Basic support (Moderate Deficiency).</li><li><strong>3</strong> – Moderate support (Developing).</li><li><strong>4</strong> – Strong support (Effective).</li><li><strong>5</strong> – Exemplary support (Leading Practice).</li></ul>",
        "The federal government's approvals processes are assessed as a 3, reflecting moderate but uneven support for the timely delivery of renewable energy and clean industry projects in Kwinana and the broader South West of Western Australia. While targeted measures signal a genuine commitment to reform, structural bottlenecks and incomplete implementation continue to constrain the pace of the energy transition.",
        "The Environment Protection and Biodiversity Conservation Act 1999 (EPBC Act) remains the primary federal environmental approvals instrument for projects that affect Matters of National Environmental Significance (MNES). For Kwinana, this applies to major industrial decarbonisation projects including hydrogen production, green ammonia, critical minerals processing, and enabling transmission infrastructure. Western Australia holds an environmental assessment bilateral agreement with the Commonwealth, in force since 2015, allowing WA's Environmental Protection Authority to conduct assessments on behalf of the federal government for many project types. An approval bilateral – which would let the state decide EPBC matters as well as assess them – does not exist and remains under negotiation: a memorandum of understanding signed in April 2026 commits both governments to a replacement assessment bilateral first, with an approvals agreement held out as a later step. This bilateral arrangement has meaningfully reduced duplication in certain cases. However, the EPBC Act still lacks a climate trigger, a critical omission that allows projects with substantial emissions impacts to proceed without federal-level climate scrutiny.",
        "Recent federal initiatives represent meaningful, if incomplete, progress. Additional resourcing for the EPBC Act and ongoing consultations on a single 'front door' for investors under the Future Made in Australia (FMiA) framework are direct responses to long-standing industry concerns about fragmented approval pathways. The FMiA framework is of particular relevance to Kwinana, given the precinct's potential role as a national hub for green hydrogen, green ammonia, and critical minerals value-adding, all priority sectors under the Act. As of mid-2025, consultations on the design of the single 'front door' are nearing completion, though implementation timelines remain uncertain. Infrastructure Australia's Gateway Review Process also plays an indirect but important role in aligning project priorities with long-term infrastructure readiness.",
        "For Kwinana to realise its potential as a national exemplar of industrial decarbonisation, further federal action is required on three fronts. First, timely finalisation and implementation of EPBC Act reforms, including the introduction of a climate trigger and strengthened strategic assessment pathways for defined industrial precincts. Second, operationalising the FMiA single 'front door' with adequate resourcing and clear service standards. Third, improved inter-agency coordination between the Commonwealth, the WA Government, and local government bodies to ensure federal approvals processes are responsive to the specific infrastructure needs and transition trajectory of regions like Kwinana.",
      ],
    },
  ],

  "federal-investment-framework": [
    {
      date: "August 2026",
      score: 3,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal support (Severe Deficiency).</li><li><strong>2</strong> – Basic support (Moderate Deficiency).</li><li><strong>3</strong> – Moderate support (Developing).</li><li><strong>4</strong> – Strong support (Effective).</li><li><strong>5</strong> – Exemplary support (Leading Practice).</li></ul>",
        "The federal government's investment framework is assessed as a 3, reflecting meaningful but uneven support for the clean energy and industrial transition investment needed in Kwinana and analogous heavy industrial precincts. The government has assembled a substantial set of financing instruments and strategic signals, but the overall architecture remains constrained by implementation gaps, coordination deficits between federal and state tiers, and continued parallel support for fossil fuel industries that sends conflicting signals to investors.",
        "The core pillars of the federal investment framework, including the Clean Energy Finance Corporation (CEFC), the Australian Renewable Energy Agency (ARENA), and the Capacity Investment Scheme (CIS), are well-established and have demonstrated capacity to catalyse investment in renewable energy generation and emerging clean technologies. In Kwinana specifically, ARENA's $19.8 million commitment to BlueScope's NeoSmelt electric smelting furnace feasibility study provides a directly relevant proof of concept. The Future Made in Australia (FMiA) Act 2024 represents the most significant structural addition to the federal investment framework in a generation, explicitly prioritising sectors with the greatest potential to contribute to net-zero goals, with critical minerals processing and clean energy manufacturing – both central to Kwinana's transition opportunity – identified as priority domains. The production tax credits announced in the 2025–26 federal budget for green aluminium and critical minerals refining are of particular strategic relevance to Kwinana.",
        "Coordination between federal and state investment frameworks remains an underdeveloped dimension. Western Australia is managing its own considerable transition investment priorities, but alignment with federal instruments in terms of timing, eligibility criteria, and sector prioritisation is inconsistent. For Kwinana, where both state and federal support are prerequisites for major projects given their scale and complexity, this misalignment increases transaction costs for investors and risks duplicating or crowding out private capital rather than complementing it.",
        "Australia's overall investment framework lags behind the scale of deployment incentives now available in comparable jurisdictions. The Inflation Reduction Act has catalysed over USD $300 billion in private clean energy investment in the United States since its passage, primarily through demand-side tax credits that create durable investment certainty independent of discretionary budget processes. Australia's framework remains more supply-side in orientation, relying on grants and concessional loans that require individual applications and co-funding negotiations. For a precinct like Kwinana, where existing operators face capital-intensive decarbonisation choices under competitive global commodity market pressure, the difference between demand-side certainty and supply-side discretion is materially significant.",
        "For the federal investment framework to achieve a higher rating, three priorities are critical. First, the production tax credits for green aluminium and critical minerals must be implemented with clear eligibility criteria, stable long-term horizons, and a Kwinana-relevant pathway that accounts for the integrated nature of the Alcoa and CSBP operations. Second, the CEFC and ARENA mandates should be explicitly broadened to include industrial decarbonisation in hard-to-abate sectors as a co-equal priority alongside renewable energy generation. Third, the federal government must establish clear and transparent exit frameworks for existing fossil fuel investment support.",
      ],
    },
  ],

  "federal-rd": [
    {
      date: "August 2026",
      score: 4,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal support (Severe Deficiency).</li><li><strong>2</strong> – Basic support (Moderate Deficiency).</li><li><strong>3</strong> – Moderate support (Developing).</li><li><strong>4</strong> – Strong support (Effective).</li><li><strong>5</strong> – Exemplary support (Leading Practice).</li></ul>",
        "The federal government's research and development policies are assessed as a 4, reflecting substantial investment, clear strategic prioritisation, and demonstrable regional relevance to Kwinana's industrial transition. The federal R&D architecture is delivering material outcomes for the precinct's hard-to-abate operators, but persistent gaps in commercialisation pathways, industrial-scale demonstration support, and the continued prominence of carbon capture and offsets within the R&D portfolio hold the indicator below leading practice.",
        "The scale of the 2024–25 and 2025–26 federal budget commitments to clean energy R&D represents the most significant structural investment in Australian decarbonisation science in a generation. Key programs, including the $1.7 billion Future Made in Australia Innovation Fund, the $1 billion Solar Sunshot Initiative, the $523.2 million Battery Breakthrough Initiative, $566 million for critical minerals research through Geoscience Australia, and the $6.7 billion Hydrogen Production Tax Incentive, together establish a diversified funding base aligned with sectors of direct importance to Kwinana.",
        "Region-specific R&D investment has a strong foothold in Kwinana. ARENA's $19.8 million commitment to BlueScope's NeoSmelt electric smelting furnace feasibility study, delivered at the Kwinana Industrial Area in partnership with Rio Tinto, BHP, and Woodside, directly targets one of the most complex decarbonisation challenges in global heavy industry: the production of primary iron from Pilbara ores without coking coal. The complementary $44.9 million ARENA commitment to Calix's Zero Emissions Steel Technology (ZESTY) demonstration plant further strengthens the national iron and steel R&D pipeline. The Western Australian research ecosystem surrounding Kwinana is a material strength. The Heavy Industry Low-carbon Transition Cooperative Research Centre (HILT CRC), headquartered at Curtin University with participation from Alcoa, Rio Tinto, Fortescue, South32, and international partners, is the pre-eminent Australian research hub for decarbonising alumina, iron, and cement – the precise industrial processes that define Kwinana's emissions profile.",
        "Despite this progress, three structural weaknesses prevent a higher rating. First, the federal R&D portfolio retains a significant allocation to carbon capture, utilisation and storage (CCUS) and carbon offsets, which risks diverting attention and capital from direct emissions reduction technologies. Second, the commercialisation and scale-up pathway between federally-funded pilot research and industrial-scale deployment remains underdeveloped – Kwinana operators consistently identify the 'missing middle', the transition from demonstration to first commercial plant, as the phase where federal support is least structured and where competing jurisdictions offer materially stronger incentives. Third, international engagement in federal R&D remains largely bilateral and project-specific; Australia has yet to embed itself as a core node in the emerging global green industrial research architecture.",
        "For the federal R&D framework to achieve a Leading Practice rating, three coordinated actions are required. First, the government should establish a dedicated hard-to-abate industrial decarbonisation R&D program with sustained funding visibility of at least ten years, explicitly covering alumina, iron and steel, green chemicals, cement, and ammonia. Second, federal R&D programs should be restructured to provide continuous support across the full technology readiness scale, from laboratory research through first-of-a-kind commercial deployment. Third, the federal government should formalise Kwinana, alongside Gladstone, the Hunter, and comparable precincts, as a designated clean industrial innovation zone, providing dedicated funding envelopes and priority positioning within international research partnerships.",
      ],
    },
  ],

  "federal-procurement": [
    {
      date: "August 2026",
      score: 3,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal support (Severe Deficiency).</li><li><strong>2</strong> – Basic support (Moderate Deficiency).</li><li><strong>3</strong> – Moderate support (Developing).</li><li><strong>4</strong> – Strong support (Effective).</li><li><strong>5</strong> – Exemplary support (Leading Practice).</li></ul>",
        "The federal government's procurement framework is assessed as a 3, reflecting moderate but uneven support for using Commonwealth purchasing power to advance zero-emissions outcomes in Kwinana and comparable industrial precincts. Core policy instruments have transitioned from proposal to active implementation over the past eighteen months, establishing a credible foundation on which to build. However, consistent application across government agencies, the generation of durable demand-side certainty, and the operational readiness of local supply chains to capture the opportunity remain works in progress.",
        "The federal procurement architecture has strengthened materially since BZE's 2025 Hunter and Gladstone assessments. The Environmentally Sustainable Procurement (ESP) Policy moved into its expanded phase on 1 July 2025, broadening its scope beyond construction services to include Information and Communication Technology, textiles, and furniture procurements above $1 million. The Future Made in Australia (FMiA) Act, supported by the Buy Australian Plan and the National Interest Framework, provides the overarching strategic rationale for using federal purchasing to build domestic industrial capability in priority clean energy and critical minerals sectors. The Capacity Investment Scheme has been streamlined to a single-stage tender and now embeds social outcomes and First Nations participation as explicit merit criteria.",
        "For Kwinana, the stakes of effective federal procurement are exceptionally high. The precinct hosts several of the assets that will determine whether Australia's heavy industry can decarbonise at pace: Alcoa's Kwinana alumina operations, the BlueScope NeoSmelt electric smelting furnace feasibility at the Kwinana Industrial Area, CSBP's ammonia and chemicals complex, and the Australian Marine Complex at Henderson – a nationally significant shipbuilding and defence industrial hub with direct exposure to Commonwealth procurement. Federal procurement of green aluminium, green iron and steel, low-carbon cement, green ammonia, and zero-emissions maritime vessels would translate policy intent into durable local demand for precisely the products Kwinana is positioned to supply.",
        "Three structural weaknesses prevent a higher rating. First, implementation consistency across federal agencies remains uneven; the ESP Policy does not yet function as a whole-of-government procurement framework, and enforcement mechanisms are underdeveloped. Second, the framework has not yet generated the demand-side certainty needed to unlock first-of-a-kind industrial investment – Commonwealth procurement has not mandated that major federally funded infrastructure must specify locally manufactured, low-emission materials. Third, supplier-side capacity support for small and medium enterprises, and in particular for First Nations-owned businesses in the South West and Pilbara supply chains, has not been scaled to match the expanded reporting and compliance expectations.",
        "For the federal procurement framework to achieve a Strong Support rating, three coordinated actions are required. First, the Commonwealth should establish binding minimum local-content and embodied-emissions requirements for all federally funded major infrastructure, transport, defence, and housing procurement – with explicit carve-outs for green steel, green aluminium, green cement, green ammonia, and critical minerals. Second, the ESP Policy should be extended to cover all federal procurement above a defined threshold, backed by transparent reporting, independent audit, and enforceable penalties for non-compliance. Third, a dedicated supplier capability program should be funded to support SMEs and First Nations businesses in the Kwinana, Pilbara, and South West supply chains.",
      ],
    },
  ],

  "state-emissions-commitment": [
    {
      date: "August 2026",
      score: 2,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal commitment (Severe Deficiency).</li><li><strong>2</strong> – Basic commitment (Moderate Deficiency).</li><li><strong>3</strong> – Moderate commitment (Developing).</li><li><strong>4</strong> – Strong commitment (Effective).</li><li><strong>5</strong> – Exemplary commitment (Leading Practice).</li></ul>",
        "The Western Australian Government's emissions reduction commitment is scored as a 2. This reflects comprehensive sectoral planning, substantial economic incentives, and proactive community engagement, offset by the absence of legislated whole-of-economy targets, a heavy reliance on federal levers, and ongoing fossil fuel expansion.",
        "Western Australia remains the only Australian jurisdiction without a legislated emissions reduction target, and the only state where emissions are still actively rising over the long term. While emissions have plateaued in recent years around 89.4 Mt CO2-e (roughly 17% above 2005 levels), this stability hides a significant gap. Aligning with a 1.5°C pathway requires a 75% reduction below 2005 levels by 2035, necessitating rapid, legally binding action. The revised Climate Action this Decade Bill 2025 includes a 2030 target, but its passage remains uncertain.",
        "Despite the legislative gap, the state faces a uniquely massive decarbonisation challenge and is building credible structural foundations. Heavy industry accounts for roughly 50% of the state's emissions, with the Pilbara alone contributing 40%. The Sectoral Emissions Reduction Strategy (SERS) represents an impressive piece of heavy lifting to address this difficult economic profile. The state is also pulling direct local levers, requiring Government Trading Enterprises to develop net zero transition plans and committing to a state-owned coal phase out by 2030. The state has deployed significant financial incentives, headlined by a $3.8 billion investment in the South West Interconnected System, the $662 million Collie Transition Package, and the $500 million Strategic Industries Fund.",
        "However, the coal phase out reveals a critical tension in WA's transition: there are significant concerns that if new renewable capacity does not come online fast enough, absolute domestic gas generation will increase to backfill the retired coal. Furthermore, for its heaviest emitters, SERS relies heavily on the federal Safeguard Mechanism to force industrial abatement rather than establishing enforceable state-based compliance mechanisms.",
        "To achieve a higher score, Western Australia must pass the Climate Action this Decade Bill 2025 with whole-of-economy interim targets. Establishing an independent oversight body with statutory authority to monitor progress and mandate ongoing engagement is also critical. Finally, ceasing support for new LNG developments and ensuring renewable energy deployment keeps pace with coal retirements, avoiding a reliance on gas backfilling, will be essential to securing a credible, enforceable path to net zero.",
      ],
    },
  ],

  "state-skills-training": [
    {
      date: "August 2026",
      score: 3,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal support (Severe Deficiency).</li><li><strong>2</strong> – Basic support (Moderate Deficiency).</li><li><strong>3</strong> – Moderate support (Developing).</li><li><strong>4</strong> – Strong support (Effective).</li><li><strong>5</strong> – Exemplary support (Leading Practice).</li></ul>",
        "The Western Australian Government's skills and training policies are scored as a 3. This score reflects a well-resourced and structurally coherent framework for the energy transition workforce, offset by the absence of a Kwinana-specific workforce transition plan and a lack of transition-specific outcome reporting.",
        "The state has made a structured, policy-integrated commitment to workforce development. The WA Renewable Hydrogen Strategy 2024-2030 explicitly identifies a skilled workforce as a key enabler of the state's clean energy ambitions, underpinned by the broader WA Climate Policy and Sectoral Emissions Reduction Strategy. The state has secured $1.2 billion in flexible funding through the five-year National Skills Agreement, complemented by significant state investments including $100 million to continue lower-fee and Fee-Free TAFE, the $16.9 million Collie Jobs and Skills Centre, and the $662 million Collie Transition Package. The state has also committed a $1 billion Strategic Industries Fund for common-user infrastructure at Strategic Industrial Areas, including Kwinana, alongside a planned Clean Energy Skills National Centre of Excellence. Meaningful progress has also been made in Aboriginal empowerment, embedded as a core enabler through equity partnership criteria in the Green Energy Approvals Initiative.",
        "The workforce delivery constraint identified in renewable energy sits squarely within the state's skills-and-training scope, but the instruments described above are not calibrated to relieve it on the timeline Kwinana's renewable pipeline requires. No current state program addresses the resources-sector wage differential driving attrition from clean energy trades; apprenticeship and Fee-Free TAFE throughput operates on a horizon mismatched to the 2026–2030 SWIS construction window; and the Strategic Industries Fund and the planned Clean Energy Skills National Centre of Excellence are oriented to building longer-term industrial capability rather than relieving near-term renewable construction delivery.",
        "The primary reason the score does not lift into the Strong Support band is the inconsistent application of region-specific workforce planning. The Collie Just Transition Model is widely regarded as a benchmark for sectoral transition, featuring tailored transition plans, skills assessments, and funded training for affected workers. However, this level of detailed planning has not been replicated in other critical industrial hubs. Kwinana is currently undergoing significant structural change, with the permanent closure of Alcoa's aluminium refinery resulting in substantial job losses continuing through 2026. There is no published Kwinana-centric workforce transition plan laying out a strategy for reskilling, redeployment, or job placement tied to energy transition outcomes.",
        "To lift this assessment into the Strong Support band, the Western Australian Government should publish a Kwinana-specific workforce transition plan modelled on the successful Collie approach. Furthermore, the state should establish an integrated energy transition workforce scorecard to track clean energy job creation and accessibility outcomes by cohort, alongside publicly reporting the clean energy share of the $1.2 billion National Skills Agreement funding.",
      ],
    },
  ],

  "state-approvals": [
    {
      date: "August 2026",
      score: 4,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal support (Severe Deficiency).</li><li><strong>2</strong> – Basic support (Moderate Deficiency).</li><li><strong>3</strong> – Moderate support (Developing).</li><li><strong>4</strong> – Strong support (Effective).</li><li><strong>5</strong> – Exemplary support (Leading Practice).</li></ul>",
        "Western Australia's approvals framework for clean energy projects is scored as a 4. This score reflects the most comprehensive structural reform of the state's regulatory architecture in a generation, resulting in drastically reduced determination timelines for many projects. However, the framework is held back from an exemplary score by inconsistent application across complex projects, hidden delays in the pre-lodgement phase, and the absence of a statutory emissions reduction test.",
        "The scale of recent improvements is evident when compared to the historical baseline. Between 2020 and 2025, chronic approval delays constrained new renewable energy installation in the South West Interconnected System to just 214 MW. Many solar, battery, and hybrid projects spent 12 to 24 months in formal assessment, while wind projects frequently exceeded two to three years. Since 2023, the government has systematically dismantled these bottlenecks through a series of mutually reinforcing reforms. The Environmental Protection Amendment Act 2024 introduced parallel decision making, allowing proponents to advance planning and ancillary approvals while environmental assessment remains underway. The Green Energy Approvals Initiative established a dedicated team within the Department of Water and Environmental Regulation to provide bespoke, streamlined pathways. The Coordinator General has been formalised under the State Development Act 2025 as a central authority to resolve bottlenecks for projects of state significance, and PoweringWA now functions as a dedicated delivery body for grid-connected projects.",
        "The combined effect of these structural changes is visible in dramatically accelerated project timelines. Synergy's Tathra Clean Energy Hub – a 1,000 MW wind, 500 MW solar, and 500 MW battery storage complex – progressed from state application to approval in approximately three to four months in late 2025 without requiring a formal environmental assessment. Similarly, Trina Solar's Killawarra Solar and Battery project received approval in approximately three months, and the Narrogin battery energy storage system moved from lodgement to approval in around five months.",
        "Despite these strong foundations, the system does not reach the highest band for three primary reasons. First, the pre-lodgement phase – which encompasses referral preparation, risk assessments, and agency consultations – remains outside statutory timeframes, commonly absorbing six months to two years before formal assessment even commences. Second, parallel processing and the full suite of reforms are applied inconsistently, with efficiency remaining highly project-dependent. Third, there is no formal statutory requirement that explicitly weights a project's contribution to emissions reduction as a criterion in approval determinations, meaning clean energy projects continue to be assessed primarily on environmental impact mitigation rather than net zero alignment.",
        "To secure a higher score, Western Australia should introduce statutory timeframes for the pre-lodgement phase to close the hidden delay window before formal assessment commences. The government should also introduce a formal emissions reduction contribution test as a statutory criterion in approval determinations. Finally, publishing aggregate approval timeline data by project type and ensuring the timely implementation of the Renewable Energy Planning Code would enhance accountability and transform WA's approvals framework from a rapidly improving system into a genuinely world-leading one.",
      ],
    },
  ],

  "state-investment-framework": [
    {
      date: "August 2026",
      score: 3,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal support (Severe Deficiency).</li><li><strong>2</strong> – Basic support (Moderate Deficiency).</li><li><strong>3</strong> – Moderate support (Developing).</li><li><strong>4</strong> – Strong support (Effective).</li><li><strong>5</strong> – Exemplary support (Leading Practice).</li></ul>",
        "The Western Australian Government's investment framework for clean energy and industrial decarbonisation is scored as a 3. The state has built a meaningful suite of investment programs and coordination tools, but their collective impact is constrained by the absence of a legislative foundation, a relatively modest national funding allocation, and fragmented delivery across multiple agencies.",
        "The centrepiece of Western Australia's investment architecture is its participation in the federal Capacity Investment Scheme through the Renewable Energy Transformation Agreement. This agreement commits the Commonwealth to underwriting 6.5 TWh of cumulative renewable generation and a minimum 1.1 GW (4.4 GWh equivalent) of dispatchable storage capacity in the state, providing a revenue floor that materially reduces financial risk for investors in the South West Interconnected System. The scheme's $70 million investment in BP's H2Kwinana facility represents a significant regional commitment, anchoring the transformation of the former oil refinery site into a green hydrogen and renewable fuels hub.",
        "This federal support is complemented by robust state-level instruments. The $1 billion Strategic Industries Fund directs enabling infrastructure investment to Strategic Industrial Areas like Kwinana, utilising first-mover rent concessions and capital rebates to lower market entry costs for large-scale clean industry projects. The New Energies Industries Funding Stream offers up to $60 million per round for direct investment attraction, while the Made in WA Energy Affordability Investment Program will provide $153.3 million in low-interest loans for clean manufacturing and energy efficiency when applications open in 2026. The statutory Coordinator General role and priority project designation process further signal strong state strategic intent to financiers.",
        "Despite these strengths, the score remains at Moderate Support due to three distinct investment gaps. First, Western Australia remains the only Australian state without a legislated interim emissions reduction or renewable energy target, meaning investors lack the legislated policy floor that underpins long-dated clean energy assets in comparable jurisdictions. Second, the state's federal Capacity Investment Scheme allocation is significantly smaller than those of eastern states, constraining the scale of revenue underwriting available and placing Western Australia at a structural disadvantage in competing for national capital. Third, investment support remains distributed across multiple departments without a single, publicly navigable entry point for clean energy proponents.",
        "To lift this assessment into the Strong Support band, the most consequential step would be the passage of the Climate Action this Decade Bill, providing the legislative foundation currently missing from the state's investment proposition. Alongside this, the government should negotiate an expanded Capacity Investment Scheme allocation that reflects the distinct infrastructure requirements of the South West Interconnected System. Finally, establishing a single integrated investment gateway that consolidates eligibility guidance across all existing state and federal programs into a unified public entry point would reduce friction for investors.",
      ],
    },
  ],

  "state-rd": [
    {
      date: "August 2026",
      score: 4,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal support (Severe Deficiency).</li><li><strong>2</strong> – Basic support (Moderate Deficiency).</li><li><strong>3</strong> – Moderate support (Developing).</li><li><strong>4</strong> – Strong support (Effective).</li><li><strong>5</strong> – Exemplary support (Leading Practice).</li></ul>",
        "WA has a healthy research and development suite of funding programs that largely sit under the 'Diversifying WA' economic development framework. This framework holds the WA Innovation Strategy and Hydrogen Strategy and a range of initiatives to build WA's 'Future State' – a global energy and manufacturing hub through the global energy transition. The score of 4 reflects strong, regionally embedded R&D investment with clear relevance to Kwinana's industrial transition.",
        "Diversifying WA's framework has included developing both greenfield and brownfield 'strategic industrial areas' (SIAs), including the Kwinana industrial area, to build WA's industrial base towards future-focused industries like green steel. Much of this is funded by the Strategic Industries Fund, which has a $1 billion allocation. The Pilbara and Mid West Hydrogen Hubs have research facilities embedded within the SIAs, demonstrating that the state government is consciously designing research and development into WA's regions as it cultivates regional hydrogen-based industrial ecosystems – essential to grow green steel, future fuels and other industry decarbonisation pathways.",
        "Key state R&D investments include $70 million of state funds in the Pilbara Hydrogen Hub in Karratha, which includes the development of a Clean Energy Training and Research Institute linked to the Burrup SIA. The Mid West Hydrogen Hub, connected to the Oakajee SIA, received $55 million and has an international dimension through the Trilateral Hydrogen Hub Feasibility Study between WA, Germany, and the Netherlands. The Clean Energy Future Fund (CEFF) is a sectoral emissions reduction strategy to fund the design, deployment, testing or demonstration of innovative clean energy projects, having delivered $26 million with the fourth round open at the time of writing. The $15 million Carbon Innovation Fund offers support for complex heavy industry solutions to be piloted.",
        "Other R&D funding streams complement these dedicated clean energy programs, including the New Industries and Innovation Fund – a $40 million fund supporting innovators from start-ups to the commercialisation and scaling phase – and $44 million in Research and Capability funding for equipment for research. While these streams are not exclusive to clean technology, they provide accessible pathways for Kwinana operators and researchers to access state support for innovation projects across the industrial decarbonisation pipeline.",
      ],
    },
  ],

  "state-procurement": [
    {
      date: "August 2026",
      score: 2,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal support (Severe Deficiency).</li><li><strong>2</strong> – Basic support (Moderate Deficiency).</li><li><strong>3</strong> – Moderate support (Developing).</li><li><strong>4</strong> – Strong support (Effective).</li><li><strong>5</strong> – Exemplary support (Leading Practice).</li></ul>",
        "WA has some excellent government procurement policies in place with the WA Buy Local for smaller projects and the WA Industry Participation Strategy (WAIPS), however the score is low because procurement is not yet directly linked to the state's emissions reduction targets, although there are signs this is coming.",
        "The WA Industry Link annual report states that since 2018, 86% of government procurement – around $52 billion – was procured through WA businesses, and that WAIPS has supported 111,467 jobs. The 2024 updated WAIP strategy includes reference to climate change and indicates that the strategy will expand, especially in the delivery of renewable energy systems. At the time of writing there are sustainable procurement guides for state procurement; however, there are no visible incentives or enforceable targets to reduce scope 3 emissions through procurement.",
        "The 2026 expression of interest for locally manufactured green steel, which closed in March, is an exciting indication of what may be coming. This kind of procurement seeds the Future State and Economic Diversification frameworks to build new future-focused industries in WA.",
        "WA has an excellent foundation of successful procurement policies. The next step is embedding and mandating emissions reduction scope for government procurement – directly linking purchasing decisions to the state's decarbonisation trajectory and creating durable demand signals for the low-carbon products that Kwinana's industrial precinct is positioned to supply.",
      ],
    },
  ],

  "lga-decarbonisation-plans": [
    {
      date: "August 2026",
      score: 2,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal Plan (Severe Deficiency).</li><li><strong>2</strong> – Basic Plan (Moderate Deficiency).</li><li><strong>3</strong> – Moderate Plan (Developing).</li><li><strong>4</strong> – Strong Plan (Effective).</li><li><strong>5</strong> – Exemplary Plan (Leading Practice).</li></ul>",
        "The Local Government Areas' (LGAs') decarbonisation plans across the Kwinana region are assessed as 2, reflecting basic but uneven progress across a complex multi-council landscape. Six LGAs encompass the region: the City of Kwinana, City of Rockingham, City of Mandurah, Shire of Murray, Shire of Serpentine-Jarrahdale, and City of Cockburn, each at different stages of climate action planning, and each confronting the particular challenge of governing alongside one of Australia's most emissions-intensive industrial precincts.",
        "Several councils demonstrate genuine commitment. The City of Kwinana has a Climate Change Plan 2021-2026 and a newly completed Environment Strategy 2024-2034 that explicitly grapples with decarbonising an LGA built around heavy industry. The City of Cockburn maintains a Climate Change Strategy 2020-2030, and the Shire of Serpentine-Jarrahdale has had a Climate Change Strategy and Local Action Plan in place since 2015. Five of the six LGAs are members of the Cities Power Partnership, and the City of Mandurah participates in the Global Covenant of Mayors for Climate & Energy, committing to a 25% renewable energy target by 2030. WALGA's collective renewable energy procurement agreement, involving 52 member councils including multiple Kwinana region LGAs, has already delivered over 42,000 tonnes CO2e in collective savings.",
        "The most distinctive initiative in the region is the Kwinana Industries Council's (KIC) Carbon Reduction Plan for the Kwinana Industrial Area (CRKIA), launched in 2020. Understood to be the only collective industrial carbon reduction program of its kind in Australia, the CRKIA brings together major enterprises across the precinct to coordinate emissions reductions covering technologies including carbon capture, wind, geothermal, and solar. The City of Kwinana's active support for this initiative reflects a pragmatic recognition that the LGA's emission profile cannot be addressed through council operations alone – a level of sophistication not found in most regional climate plans.",
        "However, none of the region's six LGAs have publicly committed to community-wide net zero targets. Plans remain largely focused on council operational efficiency, including solar panels, LED upgrades, and fleet transitions, rather than establishing structured pathways to economy-wide decarbonisation. The CRKIA, pioneering in concept, has yet to specify a net zero date or binding interim targets, which limits its value as a planning anchor. Community-wide emissions inventories are not publicly available across the region, making it impossible to track aggregate progress. Most pressingly, no LGA has developed an explicit just transition framework, a significant gap given the recent closure of major operations including BHP Nickel West, Alcoa, IGO, and Wyloo, which have already begun reshaping the region's workforce and economic base.",
        "The Kwinana region's LGAs have a meaningful foundation from which to accelerate. The state and federal government should support councils in establishing clear, measurable, community-wide emissions reduction targets, backed by dedicated resources for implementation. Formalising the CRKIA with binding interim targets and a net zero commitment date would position it as a national model for industrial precinct climate governance. A formal multi-LGA climate governance mechanism for the Kwinana region, coordinated through WALGA or the regional development commission, would enable coherent planning for the precinct's unique decarbonisation challenge and maximise the use of existing frameworks.",
      ],
    },
  ],

  "strategic-nature-positive-planning": [
    {
      date: "August 2026",
      score: 2,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal level of planning (Severe Deficiency).</li><li><strong>2</strong> – Basic level of planning (Moderate Deficiency).</li><li><strong>3</strong> – Moderate level of planning (Developing).</li><li><strong>4</strong> – Strong level of planning (Effective).</li><li><strong>5</strong> – Exemplary level of planning (Leading Practice).</li></ul>",
        "Strategic and nature-positive land-use planning scores a 2. Public data exists for biodiversity and agriculture across the state, as well as existing and commissioning energy infrastructure; however, these are generally only available as printable maps of selected areas as opposed to downloadable comprehensive GIS datasets. While statewide printable maps of threatened species and communities data exist, and a separate layer of environmentally sensitive areas, a biodiversity prioritisation dataset has not been identified. There is no public evidence of a combined biodiversity prioritisation data layer for the state.",
        "There is research being done and applied on biodiversity prioritisation and strategic land use across Perth and Peel, which includes the Kwinana and areas adjacent, but implications for renewable energy siting are not clear, and this work does not extend to the Wheatbelt. An MoU between the Western Australian Government and the Federal government to develop a bilateral agreement to coordinate and collaborate on EPBC approvals is welcome but is not due until the end of 2026. WA has a planning framework in place and a substantial integrated regional planning effort underway. However, it doesn't yet have a regional strategic planning layer, i.e. a single, spatially-explicit, cross-sectoral land-use plan or readily available comprehensive supporting information for such.",
        "The Perth–Peel Strategic Assessment, which includes the Kwinana area, explicitly mapped priority conservation areas and identified conflicts with planned development footprints, enabling significantly reduced impacts on biodiversity and informing a significant expansion of the conservation estate in the area. However, this was part of a federal-state strategic assessment and its application to future land use prioritisation around renewable energy siting is not clear, and this assessment does not include the Wheatbelt region where much of Kwinana's renewable energy supply chain will be built.",
        "The Draft Renewable Energy Planning Code (DREP), released by the WAPC for consultation from December 2025 to April 2026, is an assessment code rather than a strategic siting product. Additionally, WA does not have a Renewable Energy Zone (REZ) framework. Two other instruments of note are Data WA, a key repository of GIS datasets, and Infrastructure WA's State Infrastructure Strategy 2022, which addresses infrastructure needs across regional sections but is not an integrated land-use plan. Key recommendations to improve this score include: developing a state-wide biodiversity prioritisation layer; consolidating data and sharing across departments to create a strategic land use prioritisation layer; and finalising and releasing Regional Planning Strategies for all relevant regions.",
      ],
    },
  ],

  "wider-community-benefit-sharing": [
    {
      date: "August 2026",
      score: 3,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal level of community benefits (Severe Deficiency).</li><li><strong>2</strong> – Basic level of community benefits (Moderate Deficiency).</li><li><strong>3</strong> – Moderate level of community benefits (Developing).</li><li><strong>4</strong> – Strong level of community benefits (Effective).</li><li><strong>5</strong> – Exemplary level of community benefits (Leading Practice).</li></ul>",
        "The score of 3 reflects a moderate or 'developing' level of community benefits; however, this assessment found that community benefits and impacts were inconsistent and fragmented, and that communities supporting the SWIS to adopt renewable energy are not benefiting in an even and consistent way. Some communities are benefiting significantly and others are missing out. The implementation of the Community Benefits Guidelines is an intervention that is likely to remedy the disparity.",
        "This assessment utilises a representative sample of 11 solar, wind and battery energy storage system (BESS) projects located across the South West Interconnected System (SWIS), selected to capture assets at various stages of maturity and ensuring maximum spatial distribution across the network. The employment dimension dragged the score up: renewable energy projects tended to score higher in employment, as construction and operations and maintenance does bring jobs. Scoring becomes less consistent in other economic benefits, with some projects offering best practice standards and others with minimal additional benefits. Most projects have some kind of community benefit fund, however some have none at all. The Collie community has had proactive planning around its economic future due to the planned closure of coal-fired power stations, which appears to have influenced nearby regions to proactively seek benefits from renewable energy, while other regions had no public planning.",
        "It is important to recognise that on March 4th, 2026, PoweringWA released the Community Benefits Guidelines when BZE was midway through this assessment process. The 2026 Community Guidelines encourage but do not mandate community benefits standards and provide fixed contribution values to balance benefits to the community and commercial viability for the developers. The two regional pilot projects will be undertaken in the shires of Dandaragan and Victoria Plains, and Narrogin and West Arthur.",
        "An exciting aspect of the guidelines are the pilots for local economic development plans developed by local community groups to deliver place-based outcomes with the benefit funds. PoweringWA is appointing independent agencies to work across the communities to help develop these plans, and funding generated from renewable energy contributions will be administered by the Regional Development Commissions. Purpose-built for regional development, the Development Commissions are a unique feature of WA and a logical body to administer community benefit funds. This analysis will provide a good baseline for evaluating the impact of the Guidelines as they are implemented.",
      ],
    },
  ],

  "effective-community-engagement": [
    {
      date: "August 2026",
      score: 3,
      paragraphs: [
        "<strong>Indicator grading scale</strong><ul class=\"bulletList\" style=\"margin-top:6px\"><li><strong>1</strong> – Minimal level of communication and engagement (Severe Deficiency).</li><li><strong>2</strong> – Basic level of communication and engagement (Moderate Deficiency).</li><li><strong>3</strong> – Moderate level of communication and engagement (Developing).</li><li><strong>4</strong> – Strong level of communication and engagement (Effective).</li><li><strong>5</strong> – Exemplary level of communication and engagement (Leading Practice).</li></ul>",
        "As seen in community benefits, the engagement and participation score is moderate, however there was also a wide range of good and poor practice (or no data) among the projects assessed. This reflects that communities are having uneven and inconsistent experience of engagement and ability to participate in renewable energy projects in their regions. The Community Benefit Guidelines lay out expectations of engagement standards and link to existing resources, therefore like community benefits, this assessment may provide a useful baseline for the impact of the Guidelines on future engagement.",
        "Government Messaging and Leadership scored 3: there has been some uncertainty about system planning in the SWIS, though community engagement is a core responsibility of PoweringWA, which runs online webinars to disseminate information; however, BZE could not find evidence of any direct ground presence in the impacted communities. Government Alignment scored 2: the state and federal governments are broadly in alignment on achieving Net Zero by 2050, but the state lagged while the WA Local Government Association showed leadership publishing the Renewable Energy Community Benefits and Engagement Guide in 2025. There is also evidence of silos and different messaging from different government departments, especially from Government-owned corporations, in the lack of a comprehensive system plan for the SWIS.",
        "Developer engagement dimensions showed wide variation across the 11 projects assessed. Local proponent presence scored 3 – Perth was considered local for many projects as it was within 200 km, with scores ranging widely across the sample. Proponent Communication and Engagement scored 3, with a wide range of practice; some projects had no evidence of good engagement, while others had abundant evidence of high quality engagement and relationship building publicly available. Stakeholder involvement scored 3, with widely varying results – some projects leaving no evidence of any community involvement, and others providing community reference groups and ways for local businesses to become involved in supply chains. Grievance/Community Concerns scored 3 – there are examples of projects with no feedback or grievance mechanism and others with a number of ways to provide feedback. There is a Federal Ombudsman to resolve disputes for renewable energy projects but no state-level ombudsman.",
      ],
    },
  ],

};
