// references-kwinana.js — Sources behind the Kwinana assessment.
//
// One list per indicator, taken from the final Kwinana Regional Readiness
// Report. Unlike the Hunter and Gladstone reports, which number endnotes,
// and Port Hedland, which prints an author-date list under each indicator,
// the Kwinana report cites bare URLs inline and prints no reference list of
// its own. There is therefore no `report` number to carry: each entry is the
// URL the report linked, with a citation written from the source itself.
//
// Entries are numbered from 1 within each indicator, in the order the
// markers appear in the evidence text. criterion.html renders them under
// the assessment on the Evidence tab.
//
// All 24 assessed indicators carry a list. One entry, on
// renewable-energy-generation, is marked UNVERIFIED: the Australian
// Financial Review article behind it is paywalled, so its citation is taken
// from the URL rather than from the page.
//

window.CITY_REFERENCES = {

  "distribution-network": [
    { n: 1, cite: "Australian Energy Market Commission. (2025, December 4). Residential electricity price trends 2025.", url: "https://www.aemc.gov.au/sites/default/files/2025-12/Price%20Trends%202025_Report%20%281%29.pdf" },
    { n: 2, cite: "Australian Energy Regulator. (2025). State of the energy market 2025.", url: "https://www.aer.gov.au/publications/reports/performance/state-energy-market-2025" },
    { n: 3, cite: "Clean Energy Regulator. (2026, August 13). Small-scale installation postcode data.", url: "https://cer.gov.au/markets/reports-and-data/small-scale-installation-postcode-data" },
    { n: 4, cite: "Open Electricity. (n.d.). Energy generation in the Wholesale Electricity Market.", url: "https://explore.openelectricity.org.au/energy/wem/?range=1y&interval=1w&view=discrete-time&group=Detailed" },
    { n: 5, cite: "Australian Energy Market Operator. (n.d.). Data (WEM).", url: "https://aemo.com.au/energy-systems/electricity/wholesale-electricity-market-wem/data-wem" },
    { n: 6, cite: "Australian Renewable Energy Agency. (2025, September 1). Project Jupiter.", url: "https://arena.gov.au/projects/project-jupiter/" },
    { n: 7, cite: "Energy Policy WA. (2026, May 21). WA Residential Battery Scheme.", url: "https://www.wa.gov.au/organisation/energy-policy-wa/wa-residential-battery-scheme" },
    { n: 8, cite: "Synergy. (n.d.). WA EV Network.", url: "https://www.synergy.net.au/Our-energy/Projects/WA-EV-Network" },
    { n: 9, cite: "Synergy. (n.d.). Distributed Energy Buyback Scheme.", url: "https://www.synergy.net.au/Your-home/Manage-account/Solar-connections-and-upgrades/Distributed-Energy-Buyback-Scheme" },
    { n: 10, cite: "Electric Vehicle Council. (2025). State of EVs 2025.", url: "https://electricvehiclecouncil.com.au/wp-content/uploads/2025/10/State-of-EVs_2025_141025-2.pdf" },
    { n: 11, cite: "Western Power. (n.d.). Network Capacity Mapping Tool.", url: "https://www.westernpower.com.au/resources-education/calculators-tools/network-capacity-mapping-tool/" },
    { n: 12, cite: "Australian Renewable Energy Agency. (2025). Electrifying road freight: pathways to transition.", url: "https://arena.gov.au/assets/2025/07/AECOM-%E2%80%93-Electrifying-Road-Freight-Report.pdf" },
    { n: 13, cite: "Western Power. (2025, July 1). 2025/26 price list for the Western Power network.", url: "https://www.erawa.com.au/sites/default/files/24789/era-approved-2025-26-price-list-for-the-western-power-network.pdf" },
  ],

  "effective-community-engagement": [
    { n: 1, cite: "Clean Energy Council. (2024). Best Practice Charter.", url: "https://cleanenergycouncil.org.au/advocacy/best-practice-charter" },
    { n: 2, cite: "Western Australian Local Government Association. (2025, July). Renewable energy community benefits and engagement guide, version 1.0.", url: "https://walga.asn.au/getmedia/ea947a1a-fc88-460f-966b-7e55f511d3a2/WALGA_Renewable-Energy-Community-Benefits-and-Engagement-Guide.pdf" },
    { n: 3, cite: "Department of Climate Change, Energy, the Environment and Water. (n.d.). Renewable Energy Transformation Agreements.", url: "https://www.dcceew.gov.au/energy/renewable/renewable-energy-transformation-agreements" },
    { n: 4, cite: "Australian Energy Infrastructure Commissioner. (n.d.). Best practice community engagement.", url: "https://www.aeic.gov.au/publications/best-practice" },
    { n: 5, cite: "Western Australian Local Government Association. (2025, December 16). WALGA supports release of draft Renewable Energy Planning Code.", url: "https://walga.asn.au/media-and-resources/media-releases/walga-supports-release-of-draft-renewable-energy-planning-code" },
  ],

  "energy-storage": [
    { n: 1, cite: "Open Electricity. (n.d.). Facilities.", url: "https://openelectricity.org.au/facilities?view=list&statuses=operating,commissioning&regions=wem&fuel_techs=battery&capacity_min=100&capacity_max=341&facility=KWINANA_ESR2&fullscreen=true" },
    { n: 2, cite: "Government of Western Australia. (2026, February 19). Strong industry response for Kalgoorlie vanadium battery plan.", url: "https://www.wa.gov.au/government/media-statements/Cook%20Labor%20Government/Strong-industry-response-for-Kalgoorlie-vanadium-battery-plan-20260219" },
    { n: 3, cite: "Released Energy. (2025, May 23). Three Springs BESS.", url: "https://released.energy/three-springs-bess/" },
    { n: 4, cite: "Energy Dome. (2026, April 27). CO2 battery.", url: "https://energydome.com/co2-battery/" },
  ],

  "federal-approvals": [
    { n: 1, cite: "Minister for the Environment and Water. (2026, April 21). Faster environmental approvals on the way for Western Australia.", url: "https://minister.dcceew.gov.au/watt/media-releases/joint-media-release-faster-environmental-approvals-way-western-australia" },
    { n: 2, cite: "Department of Climate Change, Energy, the Environment and Water. (2026). Greater accountability and transparency in decision making.", url: "https://www.dcceew.gov.au/environment/epbc/epbc-act-reform/greater-accountability-transparency-decision-making" },
    { n: 3, cite: "Commonwealth of Australia. (2025, December 1). Environment Protection Reform Act 2025.", url: "https://www.legislation.gov.au/C2025A00068/asmade/text" },
    { n: 4, cite: "Department of Climate Change, Energy, the Environment and Water. (2026, August 24). New environmental standards available as more reforms begin.", url: "https://www.dcceew.gov.au/about/news/new-environmental-standards-available-as-more-reforms-begin" },
    { n: 5, cite: "Department of Climate Change, Energy, the Environment and Water. (2026, May 8). Next steps and consultations on environment reforms.", url: "https://www.dcceew.gov.au/environment/epbc/epbc-act-reform/next-steps-on-environmental-law-reform" },
    { n: 6, cite: "Minister for the Environment and Water. (2026, May 12). Budget delivers on landmark environmental law reforms.", url: "https://minister.dcceew.gov.au/watt/media-releases/budget-delivers-landmark-environmental-law-reforms" },
    { n: 7, cite: "Department of Climate Change, Energy, the Environment and Water. (2025, March 10). National Renewable Energy Priority List.", url: "https://www.dcceew.gov.au/energy/renewable/priority-list" },
    { n: 8, cite: "Department of Climate Change, Energy, the Environment and Water. (2022, December 8). Public comments and decisions on actions referred under the EPBC Act.", url: "https://www.dcceew.gov.au/environment/epbc/public-comments" },
    { n: 9, cite: "Department of the Treasury. (2024, May 14). Future Made in Australia: National Interest Framework supporting paper.", url: "https://treasury.gov.au/publication/p2024-526942" },
    { n: 10, cite: "Minister for Industry and Innovation. (2026, April 9). Building our economic resilience through the Investor Front Door.", url: "https://www.minister.industry.gov.au/t-ayres/media/building-our-economic-resilience-through-the-investor-front-door" },
    { n: 11, cite: "Heynes, G. (2026, July 15). Over 4GWh of battery storage added to Australia's updated National Renewable Energy Priority List.", url: "https://www.energy-storage.news/over-4gwh-of-battery-storage-added-to-australias-updated-national-renewable-energy-priority-list/" },
    { n: 12, cite: "Department of Climate Change, Energy, the Environment and Water. (n.d.). Capacity Investment Scheme.", url: "https://www.dcceew.gov.au/energy/renewable/capacity-investment-scheme" },
    { n: 13, cite: "Department of Climate Change, Energy, the Environment and Water. (n.d.). Indigenous heritage laws.", url: "https://www.dcceew.gov.au/parks-heritage/heritage/laws/indigenous" },
  ],

  "federal-emissions-commitment": [
    { n: 1, cite: "Beyond Zero Emissions. (2025, May). Powering up the Hunter.", url: "https://www.bze.org.au/research/report/powering-up-the-hunter" },
    { n: 2, cite: "Beyond Zero Emissions. (2025, October). Powering up Gladstone.", url: "https://www.bze.org.au/research/report/powering-up-gladstone" },
    { n: 3, cite: "Bates, A. (2026, July 25). What you should know about the legal case against extending Australia's biggest gas project.", url: "https://www.abc.net.au/news/2026-07-25/what-to-know-about-the-landmark-case-against-north-west-shelf/106953170" },
    { n: 4, cite: "Woodside Energy Group Ltd. (2025, September 12). Woodside welcomes approval of North West Shelf project extension.", url: "https://www.woodside.com/docs/default-source/media-releases/2025/woodside-welcomes-approval-of-north-west-shelf-project-extension.pdf" },
    { n: 5, cite: "Climate Council. (2026, March 23). The Albanese Government's fossil fuel approvals.", url: "https://www.climatecouncil.org.au/resources/albanese-governments-fossil-fuel-approvals/" },
    { n: 6, cite: "Department of Climate Change, Energy, the Environment and Water. (2025). Australia's 2035 nationally determined contribution.", url: "https://unfccc.int/sites/default/files/2025-09/Australias%20Second%20NDC.pdf" },
    { n: 7, cite: "Carbon Brief. (2025, May 6). Australia federal election: Anthony Albanese wins in landslide.", url: "https://www.carbonbrief.org/daily-brief/australia-federal-election-anthony-albanese-wins-in-landslide/" },
    { n: 8, cite: "Parliament of Australia. (2025, December 1). Environment Protection Reform Bill 2025.", url: "https://www.aph.gov.au/Parliamentary_Business/Bills_Legislation/Bills_Search_Results/Result?bId=r7398" },
    { n: 9, cite: "Australian Securities and Investments Commission. (2025, March 31). 25-051MR ASIC issues sustainability reporting regulatory guide.", url: "https://www.asic.gov.au/about-asic/news-centre/find-a-media-release/2025-releases/25-051mr-asic-issues-sustainability-reporting-regulatory-guide" },
    { n: 10, cite: "The Treasury. (n.d.). Future Made in Australia.", url: "https://treasury.gov.au/policy-topics/future-made-australia" },
    { n: 11, cite: "Clean Energy Regulator. (2026, April 15). Explore the 2024-25 Safeguard Mechanism data.", url: "https://cer.gov.au/news-and-media/news/2026/april/explore-2024-25-safeguard-mechanism-data" },
    { n: 12, cite: "Clean Energy Regulator. (2026, June 12). Australian environmental markets.", url: "https://cer.gov.au/markets/reports-and-data/quarterly-carbon-market-reports/quarterly-carbon-market-report-march-quarter-2026/australian-environmental-markets" },
    { n: 13, cite: "Melville-Rea, K. (2025, April 15). Latest Safeguard Mechanism data shows Australia's centrepiece climate policy is primarily a clearinghouse for low-integrity offsets.", url: "https://climateintegrity.org.au/latest/latest-safeguard-mechanism-data-shows-australias-centrepiece-climate-policy-is-primarily-a-clearinghouse-for-low-integrity-offsets" },
    { n: 14, cite: "Department of Climate Change, Energy, the Environment and Water. (2026). 2026-27 review of the Safeguard Mechanism.", url: "https://www.dcceew.gov.au/climate-change/emissions-reporting/national-greenhouse-energy-reporting-scheme/safeguard-mechanism/2026-67-review-of-the-safeguard-mechanism" },
    { n: 15, cite: "Department of Climate Change, Energy, the Environment and Water. (2025, September 18). Australia's Net Zero Plan.", url: "https://www.dcceew.gov.au/climate-change/publications/net-zero-plan" },
    { n: 16, cite: "Australian Government. (2025, September 18). Industry Sector Plan.", url: "https://www.industry.gov.au/publications/industry-sector-plan" },
    { n: 17, cite: "Australian Government. (2025, September 18). Resources Sector Plan.", url: "https://www.industry.gov.au/publications/resources-sector-plan" },
    { n: 18, cite: "Department of Climate Change, Energy, the Environment and Water. (2025, November 27). Australia's emissions projections 2025.", url: "https://www.dcceew.gov.au/climate-change/publications/australias-emissions-projections-2025" },
    { n: 19, cite: "Department of Climate Change, Energy, the Environment and Water. (2026, August 28). Quarterly update of Australia's National Greenhouse Gas Inventory: March 2026.", url: "https://www.dcceew.gov.au/sites/default/files/documents/quarterly-update-australias-national-greenhouse-gas-inventory-march-2026.pdf" },
    { n: 20, cite: "Wong, P. (2025, November 23). COP to be hosted by Türkiye with Australia leading negotiations.", url: "https://www.foreignminister.gov.au/minister/penny-wong/media-release/cop-be-hosted-turkiye-australia-leading-negotiations" },
    { n: 21, cite: "Department of Climate Change, Energy, the Environment and Water. (2026, February 13). Australia's Carbon Leakage Review report.", url: "https://www.dcceew.gov.au/climate-change/publications/carbon-leakage-review" },
    { n: 22, cite: "European Commission. (2026). CBAM definitive regime.", url: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-definitive-regime_en" },
    { n: 23, cite: "Commonwealth of Australia. (2025, December 1). Environment Protection Reform Act 2025.", url: "https://www.legislation.gov.au/C2025A00068/asmade/text" },
    { n: 24, cite: "Climate Change Authority. (2025, September 18). 2035 emissions reduction targets report.", url: "https://www.climatechangeauthority.gov.au/2035-emissions-reduction-targets-advice" },
    { n: 25, cite: "Australian Energy Market Operator. (2026, June 25). 2026 Integrated System Plan.", url: "https://www.aemo.com.au/energy-systems/major-publications/integrated-system-plan-isp/2026-integrated-system-plan-isp" },
    { n: 26, cite: "Australian Conservation Foundation. (2026, July 28). North West Shelf court case: what happened and what's next.", url: "https://www.acf.org.au/news/north-west-shelf-court-case-what-happened-and-whats-next" },
    { n: 27, cite: "Australian Government. (2026, August 19). Powering the Regions Fund: Safeguard Transformation Stream Round 2.", url: "https://business.gov.au/grants-and-programs/powering-the-regions-fund-safeguard-transformation-stream-round-2" },
    { n: 28, cite: "Alcoa Corporation. (2025, September 29). Alcoa announces closure of Kwinana refinery, also updates third quarter 2025 outlook.", url: "https://news.alcoa.com/press-releases/press-release-details/2025/Alcoa-Announces-Closure-of-Kwinana-Refinery-Also-Updates-Third-Quarter-2025-Outlook/default.aspx" },
    { n: 29, cite: "Vorrath, S. (2025, February 27). Too far, too fast: bp justifies renewables backtrack, Australian mega-projects on back-burner.", url: "https://reneweconomy.com.au/too-far-too-fast-bp-details-renewables-backtrack-puts-wa-hydrogen-mega-projects-on-ice/" },
    { n: 30, cite: "Minister for Resources and Minister for Northern Australia. (2023, November 17). $70 million investment in Kwinana Hydrogen Hub enables major step forward for WA hydrogen industry.", url: "https://minister.industry.gov.au/ministers/king/media-releases/70-million-investment-kwinana-hydrogen-hub-enables-major-step-forward-wa-hydrogen-industry" },
  ],

  "federal-investment-framework": [
    { n: 1, cite: "Clean Energy Finance Corporation. (n.d.). Home.", url: "https://www.cefc.com.au/" },
    { n: 2, cite: "Australian Renewable Energy Agency. (n.d.). Home.", url: "https://arena.gov.au/" },
    { n: 3, cite: "Department of Climate Change, Energy, the Environment and Water. (n.d.). Capacity Investment Scheme.", url: "https://www.dcceew.gov.au/energy/renewable/capacity-investment-scheme" },
    { n: 4, cite: "Australian Renewable Energy Agency. (2025, June 17). Project NeoSmelt.", url: "https://arena.gov.au/projects/project-neosmelt/" },
    { n: 5, cite: "Minister for Industry and Innovation. (n.d.). Net Zero Fund's $5 billion of world-leading decarbonisation finance.", url: "https://www.minister.industry.gov.au/t-ayres/media/net-zero-funds-5-billion-world-leading-decarbonisation-finance" },
    { n: 6, cite: "Minister for Climate Change and Energy. (n.d.). Joint media release: Delivering Australia's climate and energy transformation.", url: "https://minister.dcceew.gov.au/bowen/media-releases/joint-media-release-delivering-australias-climate-and-energy-transformation" },
    { n: 7, cite: "Department of Climate Change, Energy, the Environment and Water. (n.d.). Powering the Regions Fund.", url: "https://www.dcceew.gov.au/climate-change/emissions-reduction/powering-the-regions-fund" },
    { n: 8, cite: "Heynes, G. (2026, May 5). Australia awards 1.9GW of renewables and 3.7GWh of battery storage under CIS Tenders 5 and 6.", url: "https://www.energy-storage.news/western-australia-awards-1-9gw-of-renewables-and-3-7gwh-of-battery-storage-under-cis-tenders-5-and-6/" },
    { n: 9, cite: "Department of Industry, Science and Resources. (n.d.). About the Critical Minerals Strategic Reserve.", url: "https://www.industry.gov.au/mining-oil-and-gas/minerals/critical-minerals/critical-minerals-strategic-reserve" },
    { n: 10, cite: "Department of the Treasury. (2024). Future Made in Australia.", url: "https://treasury.gov.au/policy-topics/economy/future-made-australia" },
    { n: 11, cite: "Department of the Treasury. (2024, May 14). Future Made in Australia: National Interest Framework supporting paper.", url: "https://treasury.gov.au/publication/p2024-526942" },
    { n: 12, cite: "Australian Taxation Office. (2025, February 20). Production tax incentives.", url: "https://www.ato.gov.au/businesses-and-organisations/income-deductions-and-concessions/incentives-and-concessions/production-tax-incentives" },
  ],

  "federal-procurement": [
    { n: 1, cite: "Department of Climate Change, Energy, the Environment and Water. (2024, July 1). Environmentally Sustainable Procurement Policy.", url: "https://www.dcceew.gov.au/environment/protection/waste/sustainable-procurement/environmentally-sustainable-procurement-policy" },
    { n: 2, cite: "The Treasury. (n.d.). Future Made in Australia.", url: "https://treasury.gov.au/policy-topics/future-made-australia" },
    { n: 3, cite: "Department of Climate Change, Energy, the Environment and Water. (n.d.). Capacity Investment Scheme.", url: "https://www.dcceew.gov.au/energy/renewable/capacity-investment-scheme" },
    { n: 4, cite: "Beyond Zero Emissions. (2024, May). Make it here: Building Australia's clean industrial future.", url: "https://www.bze.org.au/research/report/make-it-here-building-australias-clean-industrial-future" },
    { n: 5, cite: "Alcoa Corporation. (2025, September 29). Alcoa announces closure of Kwinana refinery, also updates third quarter 2025 outlook.", url: "https://news.alcoa.com/press-releases/press-release-details/2025/Alcoa-Announces-Closure-of-Kwinana-Refinery-Also-Updates-Third-Quarter-2025-Outlook/default.aspx" },
    { n: 6, cite: "Australian Renewable Energy Agency. (2025, June 17). Project NeoSmelt.", url: "https://arena.gov.au/projects/project-neosmelt/" },
    { n: 7, cite: "DevelopmentWA. (n.d.). Australian Marine Complex: About the AMC.", url: "https://developmentwa.com.au/projects/industrial-and-commercial/australian-marine-complex/about-the-amc" },
  ],

  "federal-rd": [
    { n: 1, cite: "Australian Renewable Energy Agency. (2025, May 19). Future Made in Australia Innovation Fund.", url: "https://arena.gov.au/funding/future-made-in-australia-innovation-fund/" },
    { n: 2, cite: "Australian Renewable Energy Agency. (2025, September 8). Solar Sunshot.", url: "https://arena.gov.au/funding/solar-sunshot/" },
    { n: 3, cite: "Australian Renewable Energy Agency. (2026, July 7). Battery Breakthrough Initiative.", url: "https://arena.gov.au/funding/battery-breakthrough-initiative/" },
    { n: 4, cite: "Geoscience Australia. (2025, August 18). Resourcing Australia's Prosperity.", url: "https://www.ga.gov.au/scientific-topics/resourcing-australias-prosperity/about-the-program" },
    { n: 5, cite: "Australian Taxation Office. (2025, February 20). Production tax incentives.", url: "https://www.ato.gov.au/businesses-and-organisations/income-deductions-and-concessions/incentives-and-concessions/production-tax-incentives" },
    { n: 6, cite: "Department of Industry, Science and Resources. (n.d.). Cooperative Research Centres Program.", url: "https://www.industry.gov.au/science-technology-and-innovation/cooperative-research-centres-program" },
    { n: 7, cite: "Australian Renewable Energy Agency. (2025, June 17). Project NeoSmelt.", url: "https://arena.gov.au/projects/project-neosmelt/" },
    { n: 8, cite: "Maryniak, B. (2025, July 24). ARENA backs Calix with $44.9M to fire up green steel future.", url: "https://arena.gov.au/news/arena-backs-calix-with-44-9m-to-fire-up-green-steel-future/" },
    { n: 9, cite: "Rio Tinto. (2025, November 17). Rio Tinto partners with Calix to test low-emissions steel making in Western Australia, pauses BioIron.", url: "https://www.riotinto.com/en/news/releases/2025/rio-tinto-partners-with-calix-to-test-low-emissions-steel-making-in-western-australia-pauses-bioiron" },
    { n: 10, cite: "Australian Renewable Energy Agency. (2025, April 30). Yarwun hydrogen calcination pilot demonstration program.", url: "https://arena.gov.au/projects/yarwun-hydrogen-calcination-pilot-demonstration-program/" },
    { n: 11, cite: "HILT CRC. (n.d.). De-risking decarbonisation for heavy industry.", url: "https://www.hiltcrc.com.au/" },
    { n: 12, cite: "business.gov.au. (2026, August 14). Current Cooperative Research Centres (CRCs).", url: "https://business.gov.au/grants-and-programs/cooperative-research-centres-crc-grants/current-cooperative-research-centres-crcs" },
    { n: 13, cite: "Australian Government. (2025, September 18). Industry Sector Plan.", url: "https://www.industry.gov.au/publications/industry-sector-plan" },
  ],

  "federal-skills-training": [
    { n: 1, cite: "Beyond Zero Emissions. (2025, May). Powering up the Hunter.", url: "https://www.bze.org.au/research/report/powering-up-the-hunter" },
    { n: 2, cite: "Beyond Zero Emissions. (2025, October). Powering up Gladstone.", url: "https://www.bze.org.au/research/report/powering-up-gladstone" },
    { n: 3, cite: "Department of Employment and Workplace Relations. (2025, July 1). Key Apprenticeship Program.", url: "https://www.apprenticeships.gov.au/key-apprenticeship-program" },
    { n: 4, cite: "Department of Employment and Workplace Relations. (2026, May 12). Australian Apprenticeships Incentive System Budget 2026-27 factsheet.", url: "https://www.dewr.gov.au/australian-apprenticeships/resources/australian-apprenticeships-incentives-system-budget-202627-factsheet" },
    { n: 5, cite: "Prime Minister of Australia. (2023, October 17). Landmark National Skills Agreement to unlock billions.", url: "https://www.pm.gov.au/media/landmark-national-skills-agreement-unlock-billions" },
    { n: 6, cite: "Australian Government. (2026). Budget paper no. 3, part 2: Skills and workforce development.", url: "https://budget.gov.au/content/bp3/download/bp3_06_part_2_skills.pdf" },
    { n: 7, cite: "Jobs and Skills Australia. (2023, October 3). The clean energy generation: workforce needs for a net zero economy.", url: "https://www.jobsandskills.gov.au/publications/the-clean-energy-generation" },
    { n: 8, cite: "Powering Skills Organisation. (2025). Workforce plan 2025.", url: "https://poweringskills.com.au/workforce-plan-2025/" },
    { n: 9, cite: "Commonwealth of Australia. (2026, May 12). Budget measures: Budget paper no. 2, 2026-27.", url: "https://budget.gov.au/content/bp2/download/bp2_2026-27.pdf" },
    { n: 10, cite: "Commonwealth of Australia. (2025, March 27). Free TAFE Act 2025.", url: "https://www.legislation.gov.au/C2025A00026/asmade" },
    { n: 11, cite: "Department of Defence. (n.d.). Henderson Defence Precinct.", url: "https://www.defence.gov.au/business-industry/industry-capability-programs/continuous-naval-shipbuilding-sustainment-enterprise/henderson-defence-precinct" },
    { n: 12, cite: "Alcoa Corporation. (2025, September 29). Alcoa announces closure of Kwinana refinery, also updates third quarter 2025 outlook.", url: "https://news.alcoa.com/press-releases/press-release-details/2025/Alcoa-Announces-Closure-of-Kwinana-Refinery-Also-Updates-Third-Quarter-2025-Outlook/default.aspx" },
    { n: 13, cite: "Vorrath, S. (2025, February 27). Too far, too fast: bp justifies renewables backtrack, Australian mega-projects on back-burner.", url: "https://reneweconomy.com.au/too-far-too-fast-bp-details-renewables-backtrack-puts-wa-hydrogen-mega-projects-on-ice/" },
    { n: 14, cite: "Net Zero Economy Authority. (2026, April 15). NZEA Board communique April 2026.", url: "https://www.netzero.gov.au/nzea-board-communique-april-2026" },
  ],

  "housing": [
    { n: 1, cite: "Real Estate Institute of Western Australia. (n.d.). Perth and regional WA rental vacancy rates.", url: "https://reiwa.com.au/the-wa-market/rental-vacancy-rates/" },
    { n: 2, cite: "SQM Research. (n.d.). Vacancy rates.", url: "https://sqmresearch.com.au/graph_vacancy.php?region=wa::Perth&type=c&t=1" },
    { n: 3, cite: "Department of the Premier and Cabinet. (2026, May 4). AUKUS Community Taskforce.", url: "https://www.wa.gov.au/organisation/department-of-the-premier-and-cabinet/aukus-community-taskforce" },
  ],

  "hydrogen-network": [
    { n: 1, cite: "APA Group. (2024, October). Parmelia Green Hydrogen Project feasibility study summary report.", url: "https://arena.gov.au/assets/2024/11/APA-Group-Parmelia-Green-Hydrogen-Project-Feasibility-Study-Summary-Report.pdf" },
    { n: 2, cite: "ACIL Allen. (2025, February 25). Gas, liquid fuel, coal and renewable gas projections.", url: "https://www.aemo.com.au/-/media/files/major-publications/isp/2025/acil-allen-2024-fuel-price-forecast-report.pdf?la=en" },
    { n: 3, cite: "Australian Renewable Energy Agency. (2025, April 30). Yarwun hydrogen calcination pilot demonstration program.", url: "https://arena.gov.au/projects/yarwun-hydrogen-calcination-pilot-demonstration-program/" },
    { n: 4, cite: "Rio Tinto. (2025, November 17). Rio Tinto partners with Calix to test low-emissions steel making in Western Australia, pauses BioIron.", url: "https://www.riotinto.com/en/news/releases/2025/rio-tinto-partners-with-calix-to-test-low-emissions-steel-making-in-western-australia-pauses-bioiron" },
    { n: 5, cite: "Australian Renewable Energy Agency. (2025, June 17). Project NeoSmelt.", url: "https://arena.gov.au/projects/project-neosmelt/" },
    { n: 6, cite: "Baringa Partners. (2025, October). Powering Australia's green export future.", url: "https://www.ceig.org.au/wp-content/uploads/2025/11/Baringa_CEIG_Powering-Australias-green-export-future-web.pdf" },
    { n: 7, cite: "CSIRO. (2023, February 20). Hydrogen map.", url: "https://www.csiro.au/hydrogen-map" },
    { n: 8, cite: "RenewMap. (n.d.). RenewMap.", url: "https://renewmap.com.au/" },
    { n: 9, cite: "Woodside. (2026, July). Proposed H2Perth liquid hydrogen production facility.", url: "https://www.woodside.com/docs/default-source/our-business---documents-and-files/new-energy/h2perth/h2perth-general-information-sheet---august.pdf?sfvrsn=f30ca038_10&ref=boilingcold.com.au" },
    { n: 10, cite: "Environmental Protection Authority Western Australia. (2023). Ammonia Expansion Project: EPA report 1753.", url: "https://www.epa.wa.gov.au/sites/default/files/EPA_Report/EPA%20Report%201753%20-%20Ammonia%20Expansion%20Project%20-%20Assessment%20report.pdf" },
    { n: 11, cite: "APA Group. (n.d.). Parmelia Green Hydrogen Project.", url: "https://www.apa.com.au/operations-and-projects/future-energy/future-energy/parmelia-green-hydrogen-project" },
  ],

  "industry-decarbonisation-plans": [
    { n: 1, cite: "City of Kwinana. (n.d.). Kwinana Industrial Area.", url: "https://www.kwinana.wa.gov.au/business-and-development/economic-data/kwinana-industrial-area" },
    { n: 2, cite: "Wesfarmers Chemicals, Energy and Fertilisers. (2026, August 27). WesCEF's decarbonisation journey.", url: "https://wescef.com.au/wescefs-roadmap-to-net-zero/" },
    { n: 3, cite: "CSBP. (2024, April 24). Commonwealth funding to help WesCEF accelerate decarbonisation.", url: "https://csbp.com.au/blog/2024/04/24/commonwealth-funding-to-help-wescef-accelerate-decarbonisation/" },
    { n: 4, cite: "Climate Action 100+. (2025, October 10). Wesfarmers Ltd company assessment.", url: "https://www.climateaction100.org/company-assessments/wesfarmers-ltd/" },
    { n: 5, cite: "Wesfarmers Limited. (2025). 2025 annual report.", url: "https://www.wesfarmers.com.au/docs/default-source/reports/wesf-ar2025-final_interactive_spreads.pdf" },
    { n: 6, cite: "APA Group. (2024, October). Parmelia Green Hydrogen Project feasibility study summary report.", url: "https://arena.gov.au/assets/2024/11/APA-Group-Parmelia-Green-Hydrogen-Project-Feasibility-Study-Summary-Report.pdf" },
    { n: 7, cite: "Environmental Protection Authority Western Australia. (2024, November 25). Ammonia expansion project.", url: "https://www.epa.wa.gov.au/proposals/ammonia-expansion-project" },
    { n: 8, cite: "Cockburn Cement. (2022, May 3). Adbri's net zero roadmap.", url: "https://cockburncementcommunity.com.au/adbris-net-zero-roadmap/" },
    { n: 9, cite: "Cockburn Cement. (2025, July). Community update.", url: "https://cockburncementcommunity.com.au/wp-content/uploads/sites/4/2025/07/CCT027-Newsletter-Digital-2.pdf" },
    { n: 10, cite: "Covalent Lithium. (2025, August 14). Covalent Lithium achieves first product at Kwinana lithium hydroxide refinery.", url: "https://www.covalentlithium.com/news/covalent-lithium-achieves-first-product-at-kwinana-lithium-hydroxide-refinery" },
    { n: 11, cite: "Environmental Protection Authority Western Australia. (2024, November 25). Covalent lithium hydroxide refinery.", url: "https://www.epa.wa.gov.au/proposals/covalent-lithium-hydroxide-refinery" },
    { n: 12, cite: "Environmental Protection Authority Western Australia. (2021, May). Covalent lithium hydroxide refinery: report 1700.", url: "https://www.epa.wa.gov.au/sites/default/files/EPA_Report/EPA%20Report%201700_Covalent%20Lithium%20Hrdroxide%20Refinery_assessment%20report.pdf" },
    { n: 13, cite: "Tronox Holdings plc. (2026). Annual report on Form 10-K for the fiscal year ended 31 December 2025.", url: "https://www.sec.gov/Archives/edgar/data/1530804/000153080426000006/trox-20251231.htm" },
    { n: 14, cite: "Tronox Holdings plc. (2024, July 31). Tronox issues 2023 sustainability report.", url: "https://s1.q4cdn.com/960380961/files/doc_news/Tronox-Issues-2023-Sustainability-Report-2024.pdf" },
    { n: 15, cite: "Tronox Holdings plc. (2025, June 12). Tronox issues 2024 sustainability report.", url: "https://www.tronox.com/tronox-issues-2024-sustainability-report/" },
    { n: 16, cite: "Australian Renewable Energy Agency. (2026, May 20). Knode Kwinana TES deployment project.", url: "https://arena.gov.au/projects/knode-kwinana-tes-deployment-project/" },
    { n: 17, cite: "Australian Renewable Energy Agency. (2026, February 6). MGA Thermal: thermal energy storage FEED studies.", url: "https://arena.gov.au/projects/mga-thermal-thermal-energy-storage-feed-studies/" },
    { n: 18, cite: "Coogee. (2022, March 8). Our capabilities: manufacturing and supply.", url: "https://www.coogee.com.au/capabilities/manufacturing-supply/" },
    { n: 19, cite: "Kwinana Industries Council. (2026, August 10). About.", url: "https://kic.org.au/about/" },
    { n: 20, cite: "Kwinana Industries Council. (2021, June). Carbon reduction project (phase 1) report.", url: "https://kic.org.au/wp-content/uploads/2022/06/CRKIA-Phase-One-Adopted-Report_RS_June-2021.pdf" },
    { n: 21, cite: "Wikipedia. (n.d.). Kwinana oil refinery.", url: "https://en.wikipedia.org/wiki/Kwinana_Oil_Refinery" },
    { n: 22, cite: "bp. (2022, April 19). bp welcomes federal funding for green hydrogen hub at Kwinana, Western Australia.", url: "https://www.bp.com/en_au/australia/home/media/press-releases/bp-welcomes-federal-funding-for-green-hydrogen-hub-at-kwinana-western-australia.html" },
    { n: 23, cite: "Milne, P. (2025, February 3). BP puts $1b Kwinana hydrogen and clean fuel projects on ice.", url: "https://www.boilingcold.com.au/bp-puts-1b-kwinana-hydrogen-and-clean-fuel-projects-on-ice/" },
    { n: 24, cite: "CSIRO. (2026, June 24). H2Kwinana.", url: "https://research.csiro.au/hyresource/h2kwinana/" },
    { n: 25, cite: "Alcoa Corporation. (2025, September 29). Alcoa announces closure of Kwinana refinery, also updates third quarter 2025 outlook.", url: "https://news.alcoa.com/press-releases/press-release-details/2025/Alcoa-Announces-Closure-of-Kwinana-Refinery-Also-Updates-Third-Quarter-2025-Outlook/default.aspx" },
    { n: 26, cite: "Ho, C. (2025, September 30). Alcoa confirms permanent shutdown of Kwinana alumina refinery, south of Perth.", url: "https://www.abc.net.au/news/2025-09-30/alcoa-announces-permanent-closure-of-kwinana-aluminium-refinery/105833688" },
    { n: 27, cite: "BHP. (2024, July 11). Western Australia Nickel to temporarily suspend operations.", url: "https://www.bhp.com/news/media-centre/releases/2024/07/western-australia-nickel-to-temporarily-suspend-operations" },
    { n: 28, cite: "Reuters. (2025, January 24). IGO, Tianqi Lithium to cease ops at lithium hydroxide plant in Western Australia.", url: "https://www.miningweekly.com/article/igo-tianqi-lithium-to-cease-ops-at-lithium-hydroxide-plant-in-western-australia-2025-01-24" },
    { n: 29, cite: "Batten, K. (2025, November 19). IGO sees no path forward for WA lithium refinery.", url: "https://www.mining.com/igo-sees-no-path-forward-for-wa-lithium-refinery/" },
  ],

  "lga-decarbonisation-plans": [
    { n: 1, cite: "City of Kwinana. (2021). Climate Change Plan 2021-2026.", url: "https://www.kwinana.wa.gov.au/cityofkwinana/media/city-life/eh0086-climate-change-plan-2021-2026_spreads.pdf" },
    { n: 2, cite: "City of Kwinana. (2024, September 12). Environment Strategy sets key directions by 2035.", url: "https://www.kwinana.wa.gov.au/council/news/2024/september/environment-strategy-sets-key-directions-by-2035" },
    { n: 3, cite: "City of Cockburn. (2026, March 23). Climate change.", url: "https://www.cockburn.wa.gov.au/ClimateChange" },
    { n: 4, cite: "Shire of Serpentine Jarrahdale. (n.d.). Climate change action.", url: "https://www.sjshire.wa.gov.au/community/health-and-environment/sustainability-and-conservation/climate-change-action.aspx" },
    { n: 5, cite: "City of Mandurah. (n.d.). Carbon and energy.", url: "https://cityofmandurahcarbonandenergy.my.canva.site/city-of-mandurah-carbon-and-energy" },
    { n: 6, cite: "Global Covenant of Mayors for Climate and Energy Oceania. (n.d.). City of Mandurah.", url: "https://www.gcom-oceania.org/members/mandurah" },
    { n: 7, cite: "WA Local Government Association. (2025, February 24). WALGA's Sustainable Energy Supply Project.", url: "https://walga.asn.au/media-and-resources/latest-news/walga-s-sustainable-energy-project" },
    { n: 8, cite: "Kwinana Industries Council. (2021, June). Carbon reduction project (phase 1) report.", url: "https://kic.org.au/wp-content/uploads/2022/06/CRKIA-Phase-One-Adopted-Report_RS_June-2021.pdf" },
    { n: 9, cite: "City of Rockingham. (2020, February). Sustainability strategy.", url: "https://rockingham.wa.gov.au/getContentAsset/7a4021f1-3644-499c-a660-7f54ec658294/3ca954ad-3848-47c6-8f97-68cebe0b47a2/Sustainability-Strategy.pdf" },
    { n: 10, cite: "City of Rockingham. (2025, August 26). Strategic Community Plan.", url: "https://rockingham.wa.gov.au/your-city/our-vision/strategic-community-plan" },
    { n: 11, cite: "City of Rockingham. (n.d.). Planning policies, procedures and information sheets.", url: "https://rockingham.wa.gov.au/planning-and-building/lodge-an-application/planning-policies,-procedures-and-information" },
    { n: 12, cite: "City of Rockingham. (n.d.). Community plan strategies.", url: "https://rockingham.wa.gov.au/your-city/our-vision/community-plan-strategies" },
    { n: 13, cite: "Alcoa Corporation. (2025, September 29). Alcoa announces closure of Kwinana refinery, also updates third quarter 2025 outlook.", url: "https://news.alcoa.com/press-releases/press-release-details/2025/Alcoa-Announces-Closure-of-Kwinana-Refinery-Also-Updates-Third-Quarter-2025-Outlook/default.aspx" },
    { n: 14, cite: "Fenner, R. (2024, July 31). Green energy tipped as Kwinana industry's saviour after closures of BHP, Alcoa, IGO and Wyloo.", url: "https://www.soundtelegraph.com.au/news/wa/green-energy-tipped-as-kwinana-industrys-saviour-after-closures-of-bhp-alcoa-igo-and-wyloo-c-15467885" },
  ],

  "renewable-energy-generation": [
    { n: 1, cite: "Open Electricity. (n.d.). Operating facilities in the Wholesale Electricity Market.", url: "https://explore.openelectricity.org.au/facilities/wem/?status=operating" },
    { n: 2, cite: "Australian Energy Market Operator. (n.d.). Data (WEM).", url: "https://www.aemo.com.au/energy-systems/electricity/wholesale-electricity-market-wem/data-wem" },
    { n: 3, cite: "Energy Policy WA. (2026, August 7). Future Energy System Outlook.", url: "https://www.wa.gov.au/government/document-collections/future-energy-system-outlook" },
    { n: 4, cite: "Jobs and Skills Australia. (2023, October 3). The clean energy generation: workforce needs for a net zero economy.", url: "https://www.jobsandskills.gov.au/publications/the-clean-energy-generation" },
    { n: 5, cite: "Australian Financial Review. (2026, March 1). Renewables giant slashes jobs as transition pressures mount. [UNVERIFIED]", url: "https://www.afr.com/policy/energy-and-climate/renewables-giant-slashes-jobs-as-transition-pressures-mount-20260301-p5o6dj" },
    { n: 6, cite: "Western Power. (n.d.). Facilitating timely connection of critical projects.", url: "https://www.westernpower.com.au/resources-education/industry-resources/large-industry-customers-and-generators/critical-project-framework/" },
    { n: 7, cite: "Synergy Renewable Energy Development. (n.d.). Proposed Tathra Wind Farm.", url: "https://www.synergyred.net.au/proposed-tathra-wind-farm" },
    { n: 8, cite: "Government of Western Australia. (2026, March 22). Key agreements to power WA's renewable energy future.", url: "https://www.wa.gov.au/government/media-statements/Cook%20Labor%20Government/Key-agreements-to-power-WA%27s-renewable-energy-future-20260322" },
    { n: 9, cite: "Department of Energy and Economic Diversification. (2025, September). South West Interconnected System Transmission Plan.", url: "https://www.wa.gov.au/media/155887/download?inline" },
  ],

  "state-approvals": [
    { n: 1, cite: "Government of Western Australia. (2024). Environmental Protection Amendment Act 2024.", url: "https://www.legislation.wa.gov.au/legislation/statutes.nsf/law_a147455.html" },
    { n: 2, cite: "Department of the Premier and Cabinet. (2026, September 2). Priority projects.", url: "https://www.wa.gov.au/organisation/department-of-the-premier-and-cabinet/priority-projects" },
    { n: 3, cite: "Synergy Renewable Energy Development. (n.d.). Proposed Tathra Wind Farm.", url: "https://www.synergyred.net.au/proposed-tathra-wind-farm" },
    { n: 4, cite: "EPBC Act Public Portal. (n.d.). Referral summary: Tathra Wind Farm.", url: "https://epbcpublicportal.environment.gov.au/all-referrals/project-referral-summary/?id=c4deeca5-0e2c-f111-88b4-7c1e5262eacb" },
  ],

  "state-emissions-commitment": [
    { n: 1, cite: "Conservation Council of Western Australia. (2026, May 5). State's peak environment group calls for stronger climate ambition and emissions reduction.", url: "https://www.ccwa.org.au/climate_bill_emissions" },
    { n: 2, cite: "Department of Climate Change, Energy, the Environment and Water. (2026). State and territory greenhouse gas inventories: annual emissions 2024.", url: "https://www.dcceew.gov.au/climate-change/publications/national-greenhouse-accounts/state-and-territory-greenhouse-gas-inventories-annual-emissions-2024" },
    { n: 3, cite: "Ho, C. (2026, May 5). WA government preparing to abandon its emissions reduction targets, documents reveal.", url: "https://www.abc.net.au/news/2026-05-05/wa-government-abandon-interim-zero-emissions-reduction-targets/106632260" },
    { n: 4, cite: "Ho, C. (2026, May 5). WA government defends decision to abandon emissions reduction targets.", url: "https://www.abc.net.au/news/2026-05-05/wa-government-says-emissions-may-rise-as-targets-abandoned/106643606" },
    { n: 5, cite: "Department of Water and Environmental Regulation. (2023, December). Sectoral emissions reduction strategy for Western Australia.", url: "https://www.wa.gov.au/system/files/2024-07/sers-final-report-20240702.pdf" },
    { n: 6, cite: "Department of Energy and Economic Diversification. (2026, May 5). Grants: Traditional Owner Participation Support Fund.", url: "https://www.wa.gov.au/government/document-collections/grants-traditional-owner-participation-support-fund" },
  ],

  "state-investment-framework": [
    { n: 1, cite: "Assistant Minister for Climate Change and Energy. (2026, May 2). Biggest electricity boost in West Australian history.", url: "https://minister.dcceew.gov.au/wilson/media-releases/joint-media-release-biggest-electricity-boost-west-australian-history" },
    { n: 2, cite: "Parkinson, G. (2026, May 2). Six wind farms, two solar hybrids and seven-hour batteries win key CIS tenders ahead of coal closure.", url: "https://reneweconomy.com.au/six-wind-farms-two-solar-hybrids-and-seven-hour-batteries-win-key-cis-tenders-ahead-of-coal-closure/#:~:text=Six%20wind%20farms%2C%20two%20solar%20hybrids%20and,minimum%20seven-hour%20battery%20projects%20emerging%20as%20winners." },
    { n: 3, cite: "Department of Energy and Economic Diversification. (2025, November 21). Strategic Industrial Lands Activation Plan.", url: "https://www.wa.gov.au/government/publications/strategic-industrial-lands-activation-plan" },
    { n: 4, cite: "Department of Energy and Economic Diversification. (2024, July 5). Strategic Industrial Areas Rent Scheme.", url: "https://www.wa.gov.au/government/publications/strategic-industrial-areas-rent-scheme" },
    { n: 5, cite: "Department of Energy and Economic Diversification. (n.d.). New Energies Industries funding stream.", url: "https://www.investandtrade.wa.gov.au/opportunities/investment-attraction-fund/new-energies-industries-funding-stream" },
    { n: 6, cite: "Department of Energy and Economic Diversification. (2026, July 3). Made in WA Energy Affordability Investment Program.", url: "https://www.wa.gov.au/organisation/department-of-energy-and-economic-diversification/made-wa-energy-affordability-investment-program" },
    { n: 7, cite: "Department of the Premier and Cabinet. (2026, September 2). Priority projects.", url: "https://www.wa.gov.au/organisation/department-of-the-premier-and-cabinet/priority-projects" },
    { n: 8, cite: "Department of the Premier and Cabinet. (2026, September 2). Western Trade Coast State Development Area.", url: "https://www.wa.gov.au/organisation/department-of-the-premier-and-cabinet/western-trade-coast-state-development-area" },
    { n: 9, cite: "Prime Minister of Australia. (2023, August 29). $3 billion Rewiring the Nation deal to power WA jobs and growth.", url: "https://www.pm.gov.au/media/3-billion-rewiring-nation-deal-power-wa-jobs-and-growth" },
    { n: 10, cite: "Western Australian Treasury Corporation. (n.d.). Sustainable Finance Program.", url: "https://www.watc.wa.gov.au/for-investors/institutional-investors/sustainable-finance-program/" },
    { n: 11, cite: "Government of Western Australia. (2026, April 27). Government plans WA's clean energy future with $1.4 billion fund.", url: "https://www.wa.gov.au/government/media-statements/Cook%20Labor%20Government/Government-plans-WA%27s-clean-energy-future-with-%241.4-billion-fund-20260427" },
    { n: 12, cite: "Government of Western Australia. (2026, May 7). 2026-27 WA State Budget overview: Economy and jobs.", url: "https://www.ourstatebudget.wa.gov.au/2026-27/economy-and-jobs.html" },
  ],

  "state-procurement": [
    { n: 1, cite: "Department of Energy and Economic Diversification. (2026, August 31). WA Industry Link.", url: "https://www.wa.gov.au/organisation/department-of-energy-and-economic-diversification/wa-industry-link" },
    { n: 2, cite: "Department of Jobs, Tourism, Science and Innovation. (2024, August). Western Australian Industry Participation Strategy 2024.", url: "https://www.wa.gov.au/system/files/2024-08/waips-2024-final.pdf" },
    { n: 3, cite: "Department of Treasury and Finance. (2021, June 1). Environmental procurement guide.", url: "https://www.wa.gov.au/government/publications/environmental-procurement-guide-0" },
    { n: 4, cite: "Government of Western Australia. (2025, November 9). Government projects to be built with green steel that's Made in WA.", url: "https://www.wa.gov.au/government/media-statements/Cook%20Labor%20Government/Government-projects-to-be-built-with-green-steel-that%27s-Made-in-WA-20251109" },
    { n: 5, cite: "Department of Energy and Economic Diversification. (2026). Expression of interest: supply of locally manufactured green steel for major government projects.", url: "https://www.wa.gov.au/system/files/2026-02/expression_of_interest_supply_of_locally_manufactured_green_steel_for_major_government_projects.pdf" },
  ],

  "state-rd": [
    { n: 1, cite: "Department of Energy and Economic Diversification. (2024, November 25). Diversify WA: 2024 update.", url: "https://www.wa.gov.au/government/publications/diversify-wa-2024-update" },
    { n: 2, cite: "Department of Energy and Economic Diversification. (2023, April 5). Diversify WA: future state.", url: "https://www.wa.gov.au/government/publications/diversify-wa-future-state" },
    { n: 3, cite: "Government of Western Australia. (2025, June 19). Strategic industries funding doubled to secure Made in WA.", url: "https://www.wa.gov.au/government/media-statements/Cook%20Labor%20Government/Strategic-industries-funding-doubled-to-secure-Made-in-WA-20250618" },
    { n: 4, cite: "Pilbara Development Commission. (n.d.). Pilbara Hydrogen Hub.", url: "https://www.pdc.wa.gov.au/our-focus/projects/pilbara-hydrogen-hub.aspx" },
    { n: 5, cite: "Government of Western Australia. (2024, February 19). Joint media statement: Pilbara Hydrogen Hub to boost Australia's hydrogen industry.", url: "https://www.wa.gov.au/government/media-statements/Cook-Labor-Government/Joint-media-statement---Pilbara-Hydrogen-Hub-to-boost-Australia%27s-hydrogen-industry--20240219#:~:text=The%20combined%20$140%20million%20investment%20($70%20million,Government)%20will%20help%20build%20infrastructure%20to%20support" },
    { n: 6, cite: "Government of Western Australia. (2023, May 26). First companies progress move to WA's Mid-West Hydrogen Hub.", url: "https://www.wa.gov.au/government/media-statements/McGowan-Labor-Government/First-companies-progress-move-to-WA%27s-Mid-West-Hydrogen-Hub-20230526" },
    { n: 7, cite: "Department of Jobs, Tourism, Science and Innovation. (2025). TrHyHub community summary.", url: "https://www.wa.gov.au/system/files/2025-05/trhyhub_community_summary.pdf" },
    { n: 8, cite: "Government of Western Australia. (2022, April 19). McGowan Government's hydrogen projects endorsed.", url: "https://www.wa.gov.au/government/media-statements/McGowan%20Labor%20Government/McGowan-Government%27s-hydrogen-projects-endorsed-20220419#:~:text=The%20McGowan%20Government%20also%20previously,help%20companies%20take%20that%20leap.%22" },
    { n: 9, cite: "Neo, R. w. (2025, February 4). BP puts the brakes on Australia's Kwinana biofuels project.", url: "https://www.spglobal.com/energy/en/news-research/latest-news/agriculture/020425-bp-puts-the-brakes-on-australias-kwinana-biofuels-project" },
    { n: 10, cite: "Department of Water and Environmental Regulation. (2026, April 29). Clean Energy Future Fund.", url: "https://www.wa.gov.au/service/environment/environment-information-services/clean-energy-future-fund" },
    { n: 11, cite: "Department of Water and Environmental Regulation. (2026, April 14). Carbon Innovation Grants Program.", url: "https://www.wa.gov.au/service/community-services/grants-and-subsidies/carbon-innovation-grants-program" },
    { n: 12, cite: "Department of Energy and Economic Diversification. (2026, September 7). New Industries and Innovation Fund.", url: "https://www.wa.gov.au/organisation/department-of-energy-and-economic-diversification/new-industries-and-innovation-fund" },
    { n: 13, cite: "Government of Western Australia. (2024, December 24). Government announces $44 million boost to research infrastructure.", url: "https://www.wa.gov.au/government/media-statements/Cook%20Labor%20Government/Government-announces-%2444-million-boost-to-research-infrastructure--20241224" },
    { n: 14, cite: "Clean Energy Skills National Centre of Excellence. (n.d.). Applied Research Grant Program.", url: "https://cleanenergyskills.wa.gov.au/grants" },
  ],

  "state-skills-training": [
    { n: 1, cite: "Department of Energy and Economic Diversification. (2024, October 25). Western Australia's renewable hydrogen strategy 2024 to 2030.", url: "https://www.wa.gov.au/government/publications/western-australias-renewable-hydrogen-strategy-2024-2030" },
    { n: 2, cite: "Institute for Sustainable Futures. (2025, July). The Western Australian electricity workforce: Projections to 2050.", url: "https://cleanenergyskills.wa.gov.au/sites/default/files/documents/Race-for-2030-WA-Workforce-Projections-Report-2025.pdf" },
    { n: 3, cite: "Department of Training and Workforce Development. (2023, October 17). Historic National Skills Agreement between Commonwealth and State Governments.", url: "https://www.wa.gov.au/government/announcements/historic-national-skills-agreement-between-commonwealth-and-state-governments" },
    { n: 4, cite: "Government of Western Australia. (2026, May 1). Cook Labor Government delivers $216m TAFE and training boost.", url: "https://www.wa.gov.au/government/media-statements/Cook%20Labor%20Government/Cook-Labor-Government-delivers-$216m-TAFE-and-training-boost-20260501" },
    { n: 5, cite: "Department of Training and Workforce Development. (2025, July 28). Fee free and low fee training.", url: "https://www.jobsandskills.wa.gov.au/fee-free-low-fee" },
  ],

  "strategic-nature-positive-planning": [
    { n: 1, cite: "Department of Water and Environmental Regulation. (2026, March 24). Assessment bilateral agreement.", url: "https://www.wa.gov.au/service/environment/environment-information-services/assessment-bilateral-agreement" },
    { n: 2, cite: "Department of Biodiversity, Conservation and Attractions. (2026, August 5). Threatened ecological communities (DBCA-038).", url: "https://catalogue.data.wa.gov.au/dataset/threatened-ecological-communities" },
    { n: 3, cite: "Department of Water and Environmental Regulation. (n.d.). Environment Online interactive map.", url: "https://environmentonline.dwer.wa.gov.au/interactive-map/" },
    { n: 4, cite: "Landgate. (n.d.). Locate map viewer.", url: "https://maps.slip.wa.gov.au/landgate/locate/" },
    { n: 5, cite: "Biodiversity Information Office. (2024). Dandjoo biodiversity data platform.", url: "https://bio.wa.gov.au/dandjoo" },
    { n: 6, cite: "Department of Primary Industries and Regional Development. (2024, July 9). NRInfo (natural resource information) for Western Australia.", url: "https://www.dpird.wa.gov.au/environment-and-sustainability/nrinfo-for-western-australia/" },
    { n: 7, cite: "Landgate. (2026, September 8). Agricultural areas (LGATE-228).", url: "https://catalogue.data.wa.gov.au/dataset/agricultural-areas" },
    { n: 8, cite: "Open Electricity. (n.d.). Facilities.", url: "https://openelectricity.org.au/facilities" },
    { n: 9, cite: "Geoscience Australia. (2025, January 17). Electricity transmission lines.", url: "https://digital.atlas.gov.au/datasets/digitalatlas::electricity-transmission-lines/about" },
    { n: 10, cite: "Department of Climate Change, Energy, the Environment and Water. (n.d.). Western Australia bilateral agreement for environmental assessments.", url: "https://www.dcceew.gov.au/environment/epbc/approvals/state-assessments/wa" },
    { n: 11, cite: "Department of Planning, Lands and Heritage. (2021, July 29). State Planning Strategy 2050.", url: "https://www.wa.gov.au/government/publications/state-planning-strategy-2050" },
    { n: 12, cite: "Department of Planning, Lands and Heritage. (2024, February 6). New regional planning strategies for the State's regions.", url: "https://www.wa.gov.au/government/document-collections/new-regional-planning-strategies-the-states-regions" },
    { n: 13, cite: "Department of Planning, Lands and Heritage. (2026, August 7). Draft Renewable Energy Planning Code.", url: "https://www.planning.wa.gov.au/draft-renewable-energy-planning-code" },
    { n: 14, cite: "Infrastructure Western Australia. (2022). State infrastructure strategy 2022: Foundations for a stronger tomorrow.", url: "https://www.infrastructure.wa.gov.au/state-infrastructure-strategy/2022" },
    { n: 15, cite: "Department of Climate Change, Energy, the Environment and Water. (n.d.). Perth and Peel regions strategic assessment.", url: "https://www.dcceew.gov.au/environment/epbc/approvals/strategic-assessments/wa-perth-peel" },
    { n: 16, cite: "Whitehead, A. L., Kujala, H., & Wintle, B. A. (2016). Dealing with cumulative biodiversity impacts in strategic environmental assessment: A new frontier for conservation planning.", url: "https://conbio.onlinelibrary.wiley.com/doi/10.1111/conl.12260" },
  ],

  "transmission-network": [
    { n: 1, cite: "Western Power. (2024, December). Transmission System Plan 2024.", url: "https://www.westernpower.com.au/4900fc/siteassets/documents/nom/transmission-system-plan-2024.pdf" },
    { n: 2, cite: "Western Power. (n.d.). Kwinana strengthening.", url: "https://letstalkpower.westernpower.com.au/kwinana-strengthening" },
    { n: 3, cite: "Government of Western Australia, Department of Jobs, Tourism, Science and Innovation. (2024, August 19). Western Trade Coast infrastructure strategy report.", url: "https://www.wa.gov.au/system/files/2024-08/western_trade_coast_infrastructure_strategy_by_arup_14.08.2024.pdf" },
    { n: 4, cite: "Energy Policy WA. (2026, July 7). Whole of System Plan 2020.", url: "https://www.wa.gov.au/government/document-collections/whole-of-system-plan-2020" },
    { n: 5, cite: "Department of Energy and Economic Diversification. (2025, September). South West Interconnected System Transmission Plan.", url: "https://www.wa.gov.au/media/155887/download?inline" },
    { n: 6, cite: "Energy Policy WA. (2023, May). SWIS demand assessment 2023 to 2042: a future ready grid.", url: "https://www.wa.gov.au/system/files/2023-05/swisda_report.pdf" },
    { n: 7, cite: "Baringa Partners. (2025, August). Powering ahead: progressing the SWIS transition.", url: "https://www.energycouncil.com.au/media/brdkxwqv/baringa_aec_wemtransitionreport_final_report.pdf" },
    { n: 8, cite: "Government of Western Australia. (2026, March 22). Key agreements to power WA's renewable energy future.", url: "https://www.wa.gov.au/government/media-statements/Cook%20Labor%20Government/Key-agreements-to-power-WA%27s-renewable-energy-future-20260322" },
  ],

  "water-and-wastewater": [
    { n: 1, cite: "Department of Water. (2016, November). Western Trade Coast heavy industry local water supply strategy.", url: "https://www.wa.gov.au/system/files/2022-09/Western-Trade-Coast-heavy-industry-local-water-supply-strategy.PDF" },
    { n: 2, cite: "ACIL Allen. (2025, February 25). Gas, liquid fuel, coal and renewable gas projections.", url: "https://www.aemo.com.au/-/media/files/major-publications/isp/2025/acil-allen-2024-fuel-price-forecast-report.pdf?la=en" },
    { n: 3, cite: "Splitwaters. (2024, September 9). Splitwaters to supply 2.5 GW of electrolysers and EPC services for the green urea project in Australia.", url: "https://www.splitwaters.com/press_release_4.html" },
    { n: 4, cite: "Oughton, C., Anda, M., Kurup, B., & Ho, G. (2021). Water circular economy at the Kwinana Industrial Area, Western Australia: the dimensions and value of industrial symbiosis.", url: "https://kic.org.au/wp-content/uploads/2024/10/Water-Circular-Economy-at-the-Kwinana-Industrial-Area-WA_RS_2021.pdf" },
    { n: 5, cite: "Government of Western Australia. (2026, June 29). Expanded water recycling in Kwinana to boost climate resilience and support emerging industries.", url: "https://www.wa.gov.au/government/media-statements/Cook%20Labor%20Government/Expanded-water-recycling-in-Kwinana-to-boost-climate-resilience-and-support-emerging-industries-20260629" },
    { n: 6, cite: "Government of Western Australia, Department of Jobs, Tourism, Science and Innovation. (2024, August 19). Western Trade Coast infrastructure strategy report.", url: "https://www.wa.gov.au/system/files/2024-08/western_trade_coast_infrastructure_strategy_by_arup_14.08.2024.pdf" },
    { n: 7, cite: "Bourne, A. R., Bruce, J., Guthrie, M. M., Koh, L.-A., Parker, K., Mastrantonis, S., & Veljanoski, I. (2023, June 17). Identifying areas of high drought risk in southwest Western Australia.", url: "https://link.springer.com/article/10.1007/s11069-023-06065-z" },
    { n: 8, cite: "Squadron Energy. (2025, August 11). Water security one step closer for new advanced wastewater treatment plant.", url: "https://squadronenergy.com/news/water-security-one-step-closer-for-new-advanced-wastewater-treatment-plant/" },
  ],

  "wider-community-benefit-sharing": [
    { n: 1, cite: "The Next Economy. (2025, August). The Hay region economic transition roadmap: Early insights paper.", url: "https://www.hay.nsw.gov.au/Portals/0/Hay%20Economic%20Roadmap%20-%20Early%20Insights%20Paper.pdf" },
    { n: 2, cite: "Department of Energy and Economic Diversification. (n.d.). Community benefits guideline.", url: "https://stateofenergy.wa.gov.au/for-community/community-benefits-guideline" },
    { n: 3, cite: "Department of Energy and Economic Diversification. (n.d.). Community benefits guideline for large-scale renewable energy projects in the South West Interconnected System: Community benefits plans.", url: "https://www.wa.gov.au/media/159191/download?inline" },
    { n: 4, cite: "Department of Energy and Economic Diversification. (n.d.). Community benefits guideline for large-scale renewable energy projects in the South West Interconnected System: Community benefits plans pilot.", url: "https://www.wa.gov.au/media/159192/download?inline" },
  ],

};
